// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FrsPageReqIdl.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from FrsPageReqIdl.proto</summary>
public static partial class FrsPageReqIdlReflection {

  #region Descriptor
  /// <summary>File descriptor for FrsPageReqIdl.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FrsPageReqIdlReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNGcnNQYWdlUmVxSWRsLnByb3RvGg9Db21tb25SZXEucHJvdG8iwwEKDUZy",
          "c1BhZ2VSZXFJZGwSJAoEZGF0YRgBIAEoCzIWLkZyc1BhZ2VSZXFJZGwuRGF0",
          "YVJlcRqLAQoHRGF0YVJlcRIaCgZjb21tb24YJyABKAsyCi5Db21tb25SZXES",
          "CgoCa3cYASABKAkSCgoCcm4YAiABKAUSDwoHcm5fbmVlZBgDIAEoBRIPCgdp",
          "c19nb29kGAQgASgFEgsKA2NpZBgFIAEoBRIKCgJwbhgPIAEoBRIRCglzb3J0",
          "X3R5cGUYLyABKAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::CommonReqReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::FrsPageReqIdl), global::FrsPageReqIdl.Parser, new[]{ "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::FrsPageReqIdl.Types.DataReq), global::FrsPageReqIdl.Types.DataReq.Parser, new[]{ "Common", "Kw", "Rn", "RnNeed", "IsGood", "Cid", "Pn", "SortType" }, null, null, null, null)})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class FrsPageReqIdl : pb::IMessage<FrsPageReqIdl>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FrsPageReqIdl> _parser = new pb::MessageParser<FrsPageReqIdl>(() => new FrsPageReqIdl());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FrsPageReqIdl> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FrsPageReqIdlReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FrsPageReqIdl() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FrsPageReqIdl(FrsPageReqIdl other) : this() {
    data_ = other.data_ != null ? other.data_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FrsPageReqIdl Clone() {
    return new FrsPageReqIdl(this);
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 1;
  private global::FrsPageReqIdl.Types.DataReq data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::FrsPageReqIdl.Types.DataReq Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FrsPageReqIdl);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FrsPageReqIdl other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Data, other.Data)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (data_ != null) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (data_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (data_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FrsPageReqIdl other) {
    if (other == null) {
      return;
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::FrsPageReqIdl.Types.DataReq();
      }
      Data.MergeFrom(other.Data);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (data_ == null) {
            Data = new global::FrsPageReqIdl.Types.DataReq();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (data_ == null) {
            Data = new global::FrsPageReqIdl.Types.DataReq();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the FrsPageReqIdl message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class DataReq : pb::IMessage<DataReq>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<DataReq> _parser = new pb::MessageParser<DataReq>(() => new DataReq());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<DataReq> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::FrsPageReqIdl.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataReq() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataReq(DataReq other) : this() {
        common_ = other.common_ != null ? other.common_.Clone() : null;
        kw_ = other.kw_;
        rn_ = other.rn_;
        rnNeed_ = other.rnNeed_;
        isGood_ = other.isGood_;
        cid_ = other.cid_;
        pn_ = other.pn_;
        sortType_ = other.sortType_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataReq Clone() {
        return new DataReq(this);
      }

      /// <summary>Field number for the "common" field.</summary>
      public const int CommonFieldNumber = 39;
      private global::CommonReq common_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::CommonReq Common {
        get { return common_; }
        set {
          common_ = value;
        }
      }

      /// <summary>Field number for the "kw" field.</summary>
      public const int KwFieldNumber = 1;
      private string kw_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string Kw {
        get { return kw_; }
        set {
          kw_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      /// <summary>Field number for the "rn" field.</summary>
      public const int RnFieldNumber = 2;
      private int rn_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int Rn {
        get { return rn_; }
        set {
          rn_ = value;
        }
      }

      /// <summary>Field number for the "rn_need" field.</summary>
      public const int RnNeedFieldNumber = 3;
      private int rnNeed_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int RnNeed {
        get { return rnNeed_; }
        set {
          rnNeed_ = value;
        }
      }

      /// <summary>Field number for the "is_good" field.</summary>
      public const int IsGoodFieldNumber = 4;
      private int isGood_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int IsGood {
        get { return isGood_; }
        set {
          isGood_ = value;
        }
      }

      /// <summary>Field number for the "cid" field.</summary>
      public const int CidFieldNumber = 5;
      private int cid_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int Cid {
        get { return cid_; }
        set {
          cid_ = value;
        }
      }

      /// <summary>Field number for the "pn" field.</summary>
      public const int PnFieldNumber = 15;
      private int pn_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int Pn {
        get { return pn_; }
        set {
          pn_ = value;
        }
      }

      /// <summary>Field number for the "sort_type" field.</summary>
      public const int SortTypeFieldNumber = 47;
      private int sortType_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int SortType {
        get { return sortType_; }
        set {
          sortType_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as DataReq);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(DataReq other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (!object.Equals(Common, other.Common)) return false;
        if (Kw != other.Kw) return false;
        if (Rn != other.Rn) return false;
        if (RnNeed != other.RnNeed) return false;
        if (IsGood != other.IsGood) return false;
        if (Cid != other.Cid) return false;
        if (Pn != other.Pn) return false;
        if (SortType != other.SortType) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (common_ != null) hash ^= Common.GetHashCode();
        if (Kw.Length != 0) hash ^= Kw.GetHashCode();
        if (Rn != 0) hash ^= Rn.GetHashCode();
        if (RnNeed != 0) hash ^= RnNeed.GetHashCode();
        if (IsGood != 0) hash ^= IsGood.GetHashCode();
        if (Cid != 0) hash ^= Cid.GetHashCode();
        if (Pn != 0) hash ^= Pn.GetHashCode();
        if (SortType != 0) hash ^= SortType.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (Kw.Length != 0) {
          output.WriteRawTag(10);
          output.WriteString(Kw);
        }
        if (Rn != 0) {
          output.WriteRawTag(16);
          output.WriteInt32(Rn);
        }
        if (RnNeed != 0) {
          output.WriteRawTag(24);
          output.WriteInt32(RnNeed);
        }
        if (IsGood != 0) {
          output.WriteRawTag(32);
          output.WriteInt32(IsGood);
        }
        if (Cid != 0) {
          output.WriteRawTag(40);
          output.WriteInt32(Cid);
        }
        if (Pn != 0) {
          output.WriteRawTag(120);
          output.WriteInt32(Pn);
        }
        if (common_ != null) {
          output.WriteRawTag(186, 2);
          output.WriteMessage(Common);
        }
        if (SortType != 0) {
          output.WriteRawTag(248, 2);
          output.WriteInt32(SortType);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (Kw.Length != 0) {
          output.WriteRawTag(10);
          output.WriteString(Kw);
        }
        if (Rn != 0) {
          output.WriteRawTag(16);
          output.WriteInt32(Rn);
        }
        if (RnNeed != 0) {
          output.WriteRawTag(24);
          output.WriteInt32(RnNeed);
        }
        if (IsGood != 0) {
          output.WriteRawTag(32);
          output.WriteInt32(IsGood);
        }
        if (Cid != 0) {
          output.WriteRawTag(40);
          output.WriteInt32(Cid);
        }
        if (Pn != 0) {
          output.WriteRawTag(120);
          output.WriteInt32(Pn);
        }
        if (common_ != null) {
          output.WriteRawTag(186, 2);
          output.WriteMessage(Common);
        }
        if (SortType != 0) {
          output.WriteRawTag(248, 2);
          output.WriteInt32(SortType);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (common_ != null) {
          size += 2 + pb::CodedOutputStream.ComputeMessageSize(Common);
        }
        if (Kw.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Kw);
        }
        if (Rn != 0) {
          size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rn);
        }
        if (RnNeed != 0) {
          size += 1 + pb::CodedOutputStream.ComputeInt32Size(RnNeed);
        }
        if (IsGood != 0) {
          size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsGood);
        }
        if (Cid != 0) {
          size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cid);
        }
        if (Pn != 0) {
          size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pn);
        }
        if (SortType != 0) {
          size += 2 + pb::CodedOutputStream.ComputeInt32Size(SortType);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(DataReq other) {
        if (other == null) {
          return;
        }
        if (other.common_ != null) {
          if (common_ == null) {
            Common = new global::CommonReq();
          }
          Common.MergeFrom(other.Common);
        }
        if (other.Kw.Length != 0) {
          Kw = other.Kw;
        }
        if (other.Rn != 0) {
          Rn = other.Rn;
        }
        if (other.RnNeed != 0) {
          RnNeed = other.RnNeed;
        }
        if (other.IsGood != 0) {
          IsGood = other.IsGood;
        }
        if (other.Cid != 0) {
          Cid = other.Cid;
        }
        if (other.Pn != 0) {
          Pn = other.Pn;
        }
        if (other.SortType != 0) {
          SortType = other.SortType;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              Kw = input.ReadString();
              break;
            }
            case 16: {
              Rn = input.ReadInt32();
              break;
            }
            case 24: {
              RnNeed = input.ReadInt32();
              break;
            }
            case 32: {
              IsGood = input.ReadInt32();
              break;
            }
            case 40: {
              Cid = input.ReadInt32();
              break;
            }
            case 120: {
              Pn = input.ReadInt32();
              break;
            }
            case 314: {
              if (common_ == null) {
                Common = new global::CommonReq();
              }
              input.ReadMessage(Common);
              break;
            }
            case 376: {
              SortType = input.ReadInt32();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              Kw = input.ReadString();
              break;
            }
            case 16: {
              Rn = input.ReadInt32();
              break;
            }
            case 24: {
              RnNeed = input.ReadInt32();
              break;
            }
            case 32: {
              IsGood = input.ReadInt32();
              break;
            }
            case 40: {
              Cid = input.ReadInt32();
              break;
            }
            case 120: {
              Pn = input.ReadInt32();
              break;
            }
            case 314: {
              if (common_ == null) {
                Common = new global::CommonReq();
              }
              input.ReadMessage(Common);
              break;
            }
            case 376: {
              SortType = input.ReadInt32();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
