// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetForumDetailResIdl.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetForumDetailResIdl.proto</summary>
public static partial class GetForumDetailResIdlReflection {

  #region Descriptor
  /// <summary>File descriptor for GetForumDetailResIdl.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetForumDetailResIdlReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpHZXRGb3J1bURldGFpbFJlc0lkbC5wcm90bxoLRXJyb3IucHJvdG8i1wMK",
          "FEdldEZvcnVtRGV0YWlsUmVzSWRsEhUKBWVycm9yGAEgASgLMgYuRXJyb3IS",
          "KwoEZGF0YRgCIAEoCzIdLkdldEZvcnVtRGV0YWlsUmVzSWRsLkRhdGFSZXMa",
          "+gIKB0RhdGFSZXMSRAoKZm9ydW1faW5mbxgBIAEoCzIwLkdldEZvcnVtRGV0",
          "YWlsUmVzSWRsLkRhdGFSZXMuUmVjb21tZW5kRm9ydW1JbmZvEkYKDGVsZWN0",
          "aW9uX3RhYhgIIAEoCzIwLkdldEZvcnVtRGV0YWlsUmVzSWRsLkRhdGFSZXMu",
          "TWFuYWdlckVsZWN0aW9uVGFiGq8BChJSZWNvbW1lbmRGb3J1bUluZm8SDgoG",
          "YXZhdGFyGAEgASgJEhAKCGZvcnVtX2lkGAIgASgEEhIKCmZvcnVtX25hbWUY",
          "AyABKAkSFAoMbWVtYmVyX2NvdW50GAUgASgNEhQKDHRocmVhZF9jb3VudBgG",
          "IAEoDRIOCgZzbG9nYW4YByABKAkSEAoIbHYxX25hbWUYEiABKAkSFQoNYXZh",
          "dGFyX29yaWdpbhgUIAEoCRovChJNYW5hZ2VyRWxlY3Rpb25UYWISGQoRbmV3",
          "X3N0cmF0ZWd5X3RleHQYBSABKAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ErrorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetForumDetailResIdl), global::GetForumDetailResIdl.Parser, new[]{ "Error", "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::GetForumDetailResIdl.Types.DataRes), global::GetForumDetailResIdl.Types.DataRes.Parser, new[]{ "ForumInfo", "ElectionTab" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::GetForumDetailResIdl.Types.DataRes.Types.RecommendForumInfo), global::GetForumDetailResIdl.Types.DataRes.Types.RecommendForumInfo.Parser, new[]{ "Avatar", "ForumId", "ForumName", "MemberCount", "ThreadCount", "Slogan", "Lv1Name", "AvatarOrigin" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GetForumDetailResIdl.Types.DataRes.Types.ManagerElectionTab), global::GetForumDetailResIdl.Types.DataRes.Types.ManagerElectionTab.Parser, new[]{ "NewStrategyText" }, null, null, null, null)})})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GetForumDetailResIdl : pb::IMessage<GetForumDetailResIdl>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetForumDetailResIdl> _parser = new pb::MessageParser<GetForumDetailResIdl>(() => new GetForumDetailResIdl());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetForumDetailResIdl> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetForumDetailResIdlReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetForumDetailResIdl() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetForumDetailResIdl(GetForumDetailResIdl other) : this() {
    error_ = other.error_ != null ? other.error_.Clone() : null;
    data_ = other.data_ != null ? other.data_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetForumDetailResIdl Clone() {
    return new GetForumDetailResIdl(this);
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 1;
  private global::Error error_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Error Error {
    get { return error_; }
    set {
      error_ = value;
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 2;
  private global::GetForumDetailResIdl.Types.DataRes data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::GetForumDetailResIdl.Types.DataRes Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetForumDetailResIdl);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetForumDetailResIdl other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Error, other.Error)) return false;
    if (!object.Equals(Data, other.Data)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (error_ != null) hash ^= Error.GetHashCode();
    if (data_ != null) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (error_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (error_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (error_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
    }
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetForumDetailResIdl other) {
    if (other == null) {
      return;
    }
    if (other.error_ != null) {
      if (error_ == null) {
        Error = new global::Error();
      }
      Error.MergeFrom(other.Error);
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::GetForumDetailResIdl.Types.DataRes();
      }
      Data.MergeFrom(other.Data);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
        case 18: {
          if (data_ == null) {
            Data = new global::GetForumDetailResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
        case 18: {
          if (data_ == null) {
            Data = new global::GetForumDetailResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the GetForumDetailResIdl message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class DataRes : pb::IMessage<DataRes>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<DataRes> _parser = new pb::MessageParser<DataRes>(() => new DataRes());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<DataRes> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::GetForumDetailResIdl.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes(DataRes other) : this() {
        forumInfo_ = other.forumInfo_ != null ? other.forumInfo_.Clone() : null;
        electionTab_ = other.electionTab_ != null ? other.electionTab_.Clone() : null;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes Clone() {
        return new DataRes(this);
      }

      /// <summary>Field number for the "forum_info" field.</summary>
      public const int ForumInfoFieldNumber = 1;
      private global::GetForumDetailResIdl.Types.DataRes.Types.RecommendForumInfo forumInfo_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::GetForumDetailResIdl.Types.DataRes.Types.RecommendForumInfo ForumInfo {
        get { return forumInfo_; }
        set {
          forumInfo_ = value;
        }
      }

      /// <summary>Field number for the "election_tab" field.</summary>
      public const int ElectionTabFieldNumber = 8;
      private global::GetForumDetailResIdl.Types.DataRes.Types.ManagerElectionTab electionTab_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::GetForumDetailResIdl.Types.DataRes.Types.ManagerElectionTab ElectionTab {
        get { return electionTab_; }
        set {
          electionTab_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as DataRes);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(DataRes other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (!object.Equals(ForumInfo, other.ForumInfo)) return false;
        if (!object.Equals(ElectionTab, other.ElectionTab)) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (forumInfo_ != null) hash ^= ForumInfo.GetHashCode();
        if (electionTab_ != null) hash ^= ElectionTab.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (forumInfo_ != null) {
          output.WriteRawTag(10);
          output.WriteMessage(ForumInfo);
        }
        if (electionTab_ != null) {
          output.WriteRawTag(66);
          output.WriteMessage(ElectionTab);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (forumInfo_ != null) {
          output.WriteRawTag(10);
          output.WriteMessage(ForumInfo);
        }
        if (electionTab_ != null) {
          output.WriteRawTag(66);
          output.WriteMessage(ElectionTab);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (forumInfo_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(ForumInfo);
        }
        if (electionTab_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElectionTab);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(DataRes other) {
        if (other == null) {
          return;
        }
        if (other.forumInfo_ != null) {
          if (forumInfo_ == null) {
            ForumInfo = new global::GetForumDetailResIdl.Types.DataRes.Types.RecommendForumInfo();
          }
          ForumInfo.MergeFrom(other.ForumInfo);
        }
        if (other.electionTab_ != null) {
          if (electionTab_ == null) {
            ElectionTab = new global::GetForumDetailResIdl.Types.DataRes.Types.ManagerElectionTab();
          }
          ElectionTab.MergeFrom(other.ElectionTab);
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              if (forumInfo_ == null) {
                ForumInfo = new global::GetForumDetailResIdl.Types.DataRes.Types.RecommendForumInfo();
              }
              input.ReadMessage(ForumInfo);
              break;
            }
            case 66: {
              if (electionTab_ == null) {
                ElectionTab = new global::GetForumDetailResIdl.Types.DataRes.Types.ManagerElectionTab();
              }
              input.ReadMessage(ElectionTab);
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              if (forumInfo_ == null) {
                ForumInfo = new global::GetForumDetailResIdl.Types.DataRes.Types.RecommendForumInfo();
              }
              input.ReadMessage(ForumInfo);
              break;
            }
            case 66: {
              if (electionTab_ == null) {
                ElectionTab = new global::GetForumDetailResIdl.Types.DataRes.Types.ManagerElectionTab();
              }
              input.ReadMessage(ElectionTab);
              break;
            }
          }
        }
      }
      #endif

      #region Nested types
      /// <summary>Container for nested types declared in the DataRes message type.</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static partial class Types {
        [global::System.SerializableAttribute]
        [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
        public sealed partial class RecommendForumInfo : pb::IMessage<RecommendForumInfo>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<RecommendForumInfo> _parser = new pb::MessageParser<RecommendForumInfo>(() => new RecommendForumInfo());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pb::MessageParser<RecommendForumInfo> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::GetForumDetailResIdl.Types.DataRes.Descriptor.NestedTypes[0]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public RecommendForumInfo() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public RecommendForumInfo(RecommendForumInfo other) : this() {
            avatar_ = other.avatar_;
            forumId_ = other.forumId_;
            forumName_ = other.forumName_;
            memberCount_ = other.memberCount_;
            threadCount_ = other.threadCount_;
            slogan_ = other.slogan_;
            lv1Name_ = other.lv1Name_;
            avatarOrigin_ = other.avatarOrigin_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public RecommendForumInfo Clone() {
            return new RecommendForumInfo(this);
          }

          /// <summary>Field number for the "avatar" field.</summary>
          public const int AvatarFieldNumber = 1;
          private string avatar_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string Avatar {
            get { return avatar_; }
            set {
              avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "forum_id" field.</summary>
          public const int ForumIdFieldNumber = 2;
          private ulong forumId_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public ulong ForumId {
            get { return forumId_; }
            set {
              forumId_ = value;
            }
          }

          /// <summary>Field number for the "forum_name" field.</summary>
          public const int ForumNameFieldNumber = 3;
          private string forumName_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string ForumName {
            get { return forumName_; }
            set {
              forumName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "member_count" field.</summary>
          public const int MemberCountFieldNumber = 5;
          private uint memberCount_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public uint MemberCount {
            get { return memberCount_; }
            set {
              memberCount_ = value;
            }
          }

          /// <summary>Field number for the "thread_count" field.</summary>
          public const int ThreadCountFieldNumber = 6;
          private uint threadCount_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public uint ThreadCount {
            get { return threadCount_; }
            set {
              threadCount_ = value;
            }
          }

          /// <summary>Field number for the "slogan" field.</summary>
          public const int SloganFieldNumber = 7;
          private string slogan_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string Slogan {
            get { return slogan_; }
            set {
              slogan_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "lv1_name" field.</summary>
          public const int Lv1NameFieldNumber = 18;
          private string lv1Name_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string Lv1Name {
            get { return lv1Name_; }
            set {
              lv1Name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "avatar_origin" field.</summary>
          public const int AvatarOriginFieldNumber = 20;
          private string avatarOrigin_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string AvatarOrigin {
            get { return avatarOrigin_; }
            set {
              avatarOrigin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override bool Equals(object other) {
            return Equals(other as RecommendForumInfo);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool Equals(RecommendForumInfo other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (Avatar != other.Avatar) return false;
            if (ForumId != other.ForumId) return false;
            if (ForumName != other.ForumName) return false;
            if (MemberCount != other.MemberCount) return false;
            if (ThreadCount != other.ThreadCount) return false;
            if (Slogan != other.Slogan) return false;
            if (Lv1Name != other.Lv1Name) return false;
            if (AvatarOrigin != other.AvatarOrigin) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override int GetHashCode() {
            int hash = 1;
            if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
            if (ForumId != 0UL) hash ^= ForumId.GetHashCode();
            if (ForumName.Length != 0) hash ^= ForumName.GetHashCode();
            if (MemberCount != 0) hash ^= MemberCount.GetHashCode();
            if (ThreadCount != 0) hash ^= ThreadCount.GetHashCode();
            if (Slogan.Length != 0) hash ^= Slogan.GetHashCode();
            if (Lv1Name.Length != 0) hash ^= Lv1Name.GetHashCode();
            if (AvatarOrigin.Length != 0) hash ^= AvatarOrigin.GetHashCode();
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (Avatar.Length != 0) {
              output.WriteRawTag(10);
              output.WriteString(Avatar);
            }
            if (ForumId != 0UL) {
              output.WriteRawTag(16);
              output.WriteUInt64(ForumId);
            }
            if (ForumName.Length != 0) {
              output.WriteRawTag(26);
              output.WriteString(ForumName);
            }
            if (MemberCount != 0) {
              output.WriteRawTag(40);
              output.WriteUInt32(MemberCount);
            }
            if (ThreadCount != 0) {
              output.WriteRawTag(48);
              output.WriteUInt32(ThreadCount);
            }
            if (Slogan.Length != 0) {
              output.WriteRawTag(58);
              output.WriteString(Slogan);
            }
            if (Lv1Name.Length != 0) {
              output.WriteRawTag(146, 1);
              output.WriteString(Lv1Name);
            }
            if (AvatarOrigin.Length != 0) {
              output.WriteRawTag(162, 1);
              output.WriteString(AvatarOrigin);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (Avatar.Length != 0) {
              output.WriteRawTag(10);
              output.WriteString(Avatar);
            }
            if (ForumId != 0UL) {
              output.WriteRawTag(16);
              output.WriteUInt64(ForumId);
            }
            if (ForumName.Length != 0) {
              output.WriteRawTag(26);
              output.WriteString(ForumName);
            }
            if (MemberCount != 0) {
              output.WriteRawTag(40);
              output.WriteUInt32(MemberCount);
            }
            if (ThreadCount != 0) {
              output.WriteRawTag(48);
              output.WriteUInt32(ThreadCount);
            }
            if (Slogan.Length != 0) {
              output.WriteRawTag(58);
              output.WriteString(Slogan);
            }
            if (Lv1Name.Length != 0) {
              output.WriteRawTag(146, 1);
              output.WriteString(Lv1Name);
            }
            if (AvatarOrigin.Length != 0) {
              output.WriteRawTag(162, 1);
              output.WriteString(AvatarOrigin);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int CalculateSize() {
            int size = 0;
            if (Avatar.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
            }
            if (ForumId != 0UL) {
              size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ForumId);
            }
            if (ForumName.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(ForumName);
            }
            if (MemberCount != 0) {
              size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MemberCount);
            }
            if (ThreadCount != 0) {
              size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ThreadCount);
            }
            if (Slogan.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(Slogan);
            }
            if (Lv1Name.Length != 0) {
              size += 2 + pb::CodedOutputStream.ComputeStringSize(Lv1Name);
            }
            if (AvatarOrigin.Length != 0) {
              size += 2 + pb::CodedOutputStream.ComputeStringSize(AvatarOrigin);
            }
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(RecommendForumInfo other) {
            if (other == null) {
              return;
            }
            if (other.Avatar.Length != 0) {
              Avatar = other.Avatar;
            }
            if (other.ForumId != 0UL) {
              ForumId = other.ForumId;
            }
            if (other.ForumName.Length != 0) {
              ForumName = other.ForumName;
            }
            if (other.MemberCount != 0) {
              MemberCount = other.MemberCount;
            }
            if (other.ThreadCount != 0) {
              ThreadCount = other.ThreadCount;
            }
            if (other.Slogan.Length != 0) {
              Slogan = other.Slogan;
            }
            if (other.Lv1Name.Length != 0) {
              Lv1Name = other.Lv1Name;
            }
            if (other.AvatarOrigin.Length != 0) {
              AvatarOrigin = other.AvatarOrigin;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 10: {
                  Avatar = input.ReadString();
                  break;
                }
                case 16: {
                  ForumId = input.ReadUInt64();
                  break;
                }
                case 26: {
                  ForumName = input.ReadString();
                  break;
                }
                case 40: {
                  MemberCount = input.ReadUInt32();
                  break;
                }
                case 48: {
                  ThreadCount = input.ReadUInt32();
                  break;
                }
                case 58: {
                  Slogan = input.ReadString();
                  break;
                }
                case 146: {
                  Lv1Name = input.ReadString();
                  break;
                }
                case 162: {
                  AvatarOrigin = input.ReadString();
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 10: {
                  Avatar = input.ReadString();
                  break;
                }
                case 16: {
                  ForumId = input.ReadUInt64();
                  break;
                }
                case 26: {
                  ForumName = input.ReadString();
                  break;
                }
                case 40: {
                  MemberCount = input.ReadUInt32();
                  break;
                }
                case 48: {
                  ThreadCount = input.ReadUInt32();
                  break;
                }
                case 58: {
                  Slogan = input.ReadString();
                  break;
                }
                case 146: {
                  Lv1Name = input.ReadString();
                  break;
                }
                case 162: {
                  AvatarOrigin = input.ReadString();
                  break;
                }
              }
            }
          }
          #endif

        }

        [global::System.SerializableAttribute]
        [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
        public sealed partial class ManagerElectionTab : pb::IMessage<ManagerElectionTab>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<ManagerElectionTab> _parser = new pb::MessageParser<ManagerElectionTab>(() => new ManagerElectionTab());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pb::MessageParser<ManagerElectionTab> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::GetForumDetailResIdl.Types.DataRes.Descriptor.NestedTypes[1]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public ManagerElectionTab() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public ManagerElectionTab(ManagerElectionTab other) : this() {
            newStrategyText_ = other.newStrategyText_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public ManagerElectionTab Clone() {
            return new ManagerElectionTab(this);
          }

          /// <summary>Field number for the "new_strategy_text" field.</summary>
          public const int NewStrategyTextFieldNumber = 5;
          private string newStrategyText_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string NewStrategyText {
            get { return newStrategyText_; }
            set {
              newStrategyText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override bool Equals(object other) {
            return Equals(other as ManagerElectionTab);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool Equals(ManagerElectionTab other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (NewStrategyText != other.NewStrategyText) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override int GetHashCode() {
            int hash = 1;
            if (NewStrategyText.Length != 0) hash ^= NewStrategyText.GetHashCode();
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (NewStrategyText.Length != 0) {
              output.WriteRawTag(42);
              output.WriteString(NewStrategyText);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (NewStrategyText.Length != 0) {
              output.WriteRawTag(42);
              output.WriteString(NewStrategyText);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int CalculateSize() {
            int size = 0;
            if (NewStrategyText.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(NewStrategyText);
            }
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(ManagerElectionTab other) {
            if (other == null) {
              return;
            }
            if (other.NewStrategyText.Length != 0) {
              NewStrategyText = other.NewStrategyText;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 42: {
                  NewStrategyText = input.ReadString();
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 42: {
                  NewStrategyText = input.ReadString();
                  break;
                }
              }
            }
          }
          #endif

        }

      }
      #endregion

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
