// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProfileReqIdl.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProfileReqIdl.proto</summary>
public static partial class ProfileReqIdlReflection {

  #region Descriptor
  /// <summary>File descriptor for ProfileReqIdl.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProfileReqIdlReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNQcm9maWxlUmVxSWRsLnByb3RvGg9Db21tb25SZXEucHJvdG8iugEKDVBy",
          "b2ZpbGVSZXFJZGwSJAoEZGF0YRgBIAEoCzIWLlByb2ZpbGVSZXFJZGwuRGF0",
          "YVJlcRqCAQoHRGF0YVJlcRILCgN1aWQYASABKAMSFwoPbmVlZF9wb3N0X2Nv",
          "dW50GAIgASgNEgoKAnBuGAYgASgNEhoKBmNvbW1vbhgJIAEoCzIKLkNvbW1v",
          "blJlcRIMCgRwYWdlGA8gASgFEhsKE2ZyaWVuZF91aWRfcG9ydHJhaXQYECAB",
          "KAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::CommonReqReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProfileReqIdl), global::ProfileReqIdl.Parser, new[]{ "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProfileReqIdl.Types.DataReq), global::ProfileReqIdl.Types.DataReq.Parser, new[]{ "Uid", "NeedPostCount", "Pn", "Common", "Page", "FriendUidPortrait" }, null, null, null, null)})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ProfileReqIdl : pb::IMessage<ProfileReqIdl>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProfileReqIdl> _parser = new pb::MessageParser<ProfileReqIdl>(() => new ProfileReqIdl());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProfileReqIdl> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProfileReqIdlReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProfileReqIdl() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProfileReqIdl(ProfileReqIdl other) : this() {
    data_ = other.data_ != null ? other.data_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProfileReqIdl Clone() {
    return new ProfileReqIdl(this);
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 1;
  private global::ProfileReqIdl.Types.DataReq data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProfileReqIdl.Types.DataReq Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProfileReqIdl);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProfileReqIdl other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Data, other.Data)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (data_ != null) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (data_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (data_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProfileReqIdl other) {
    if (other == null) {
      return;
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::ProfileReqIdl.Types.DataReq();
      }
      Data.MergeFrom(other.Data);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (data_ == null) {
            Data = new global::ProfileReqIdl.Types.DataReq();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (data_ == null) {
            Data = new global::ProfileReqIdl.Types.DataReq();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the ProfileReqIdl message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class DataReq : pb::IMessage<DataReq>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<DataReq> _parser = new pb::MessageParser<DataReq>(() => new DataReq());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<DataReq> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::ProfileReqIdl.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataReq() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataReq(DataReq other) : this() {
        uid_ = other.uid_;
        needPostCount_ = other.needPostCount_;
        pn_ = other.pn_;
        common_ = other.common_ != null ? other.common_.Clone() : null;
        page_ = other.page_;
        friendUidPortrait_ = other.friendUidPortrait_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataReq Clone() {
        return new DataReq(this);
      }

      /// <summary>Field number for the "uid" field.</summary>
      public const int UidFieldNumber = 1;
      private long uid_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public long Uid {
        get { return uid_; }
        set {
          uid_ = value;
        }
      }

      /// <summary>Field number for the "need_post_count" field.</summary>
      public const int NeedPostCountFieldNumber = 2;
      private uint needPostCount_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint NeedPostCount {
        get { return needPostCount_; }
        set {
          needPostCount_ = value;
        }
      }

      /// <summary>Field number for the "pn" field.</summary>
      public const int PnFieldNumber = 6;
      private uint pn_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint Pn {
        get { return pn_; }
        set {
          pn_ = value;
        }
      }

      /// <summary>Field number for the "common" field.</summary>
      public const int CommonFieldNumber = 9;
      private global::CommonReq common_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::CommonReq Common {
        get { return common_; }
        set {
          common_ = value;
        }
      }

      /// <summary>Field number for the "page" field.</summary>
      public const int PageFieldNumber = 15;
      private int page_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int Page {
        get { return page_; }
        set {
          page_ = value;
        }
      }

      /// <summary>Field number for the "friend_uid_portrait" field.</summary>
      public const int FriendUidPortraitFieldNumber = 16;
      private string friendUidPortrait_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string FriendUidPortrait {
        get { return friendUidPortrait_; }
        set {
          friendUidPortrait_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as DataReq);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(DataReq other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (Uid != other.Uid) return false;
        if (NeedPostCount != other.NeedPostCount) return false;
        if (Pn != other.Pn) return false;
        if (!object.Equals(Common, other.Common)) return false;
        if (Page != other.Page) return false;
        if (FriendUidPortrait != other.FriendUidPortrait) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (Uid != 0L) hash ^= Uid.GetHashCode();
        if (NeedPostCount != 0) hash ^= NeedPostCount.GetHashCode();
        if (Pn != 0) hash ^= Pn.GetHashCode();
        if (common_ != null) hash ^= Common.GetHashCode();
        if (Page != 0) hash ^= Page.GetHashCode();
        if (FriendUidPortrait.Length != 0) hash ^= FriendUidPortrait.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (Uid != 0L) {
          output.WriteRawTag(8);
          output.WriteInt64(Uid);
        }
        if (NeedPostCount != 0) {
          output.WriteRawTag(16);
          output.WriteUInt32(NeedPostCount);
        }
        if (Pn != 0) {
          output.WriteRawTag(48);
          output.WriteUInt32(Pn);
        }
        if (common_ != null) {
          output.WriteRawTag(74);
          output.WriteMessage(Common);
        }
        if (Page != 0) {
          output.WriteRawTag(120);
          output.WriteInt32(Page);
        }
        if (FriendUidPortrait.Length != 0) {
          output.WriteRawTag(130, 1);
          output.WriteString(FriendUidPortrait);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (Uid != 0L) {
          output.WriteRawTag(8);
          output.WriteInt64(Uid);
        }
        if (NeedPostCount != 0) {
          output.WriteRawTag(16);
          output.WriteUInt32(NeedPostCount);
        }
        if (Pn != 0) {
          output.WriteRawTag(48);
          output.WriteUInt32(Pn);
        }
        if (common_ != null) {
          output.WriteRawTag(74);
          output.WriteMessage(Common);
        }
        if (Page != 0) {
          output.WriteRawTag(120);
          output.WriteInt32(Page);
        }
        if (FriendUidPortrait.Length != 0) {
          output.WriteRawTag(130, 1);
          output.WriteString(FriendUidPortrait);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (Uid != 0L) {
          size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
        }
        if (NeedPostCount != 0) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NeedPostCount);
        }
        if (Pn != 0) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Pn);
        }
        if (common_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(Common);
        }
        if (Page != 0) {
          size += 1 + pb::CodedOutputStream.ComputeInt32Size(Page);
        }
        if (FriendUidPortrait.Length != 0) {
          size += 2 + pb::CodedOutputStream.ComputeStringSize(FriendUidPortrait);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(DataReq other) {
        if (other == null) {
          return;
        }
        if (other.Uid != 0L) {
          Uid = other.Uid;
        }
        if (other.NeedPostCount != 0) {
          NeedPostCount = other.NeedPostCount;
        }
        if (other.Pn != 0) {
          Pn = other.Pn;
        }
        if (other.common_ != null) {
          if (common_ == null) {
            Common = new global::CommonReq();
          }
          Common.MergeFrom(other.Common);
        }
        if (other.Page != 0) {
          Page = other.Page;
        }
        if (other.FriendUidPortrait.Length != 0) {
          FriendUidPortrait = other.FriendUidPortrait;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 8: {
              Uid = input.ReadInt64();
              break;
            }
            case 16: {
              NeedPostCount = input.ReadUInt32();
              break;
            }
            case 48: {
              Pn = input.ReadUInt32();
              break;
            }
            case 74: {
              if (common_ == null) {
                Common = new global::CommonReq();
              }
              input.ReadMessage(Common);
              break;
            }
            case 120: {
              Page = input.ReadInt32();
              break;
            }
            case 130: {
              FriendUidPortrait = input.ReadString();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 8: {
              Uid = input.ReadInt64();
              break;
            }
            case 16: {
              NeedPostCount = input.ReadUInt32();
              break;
            }
            case 48: {
              Pn = input.ReadUInt32();
              break;
            }
            case 74: {
              if (common_ == null) {
                Common = new global::CommonReq();
              }
              input.ReadMessage(Common);
              break;
            }
            case 120: {
              Page = input.ReadInt32();
              break;
            }
            case 130: {
              FriendUidPortrait = input.ReadString();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
