// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProfileResIdl.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProfileResIdl.proto</summary>
public static partial class ProfileResIdlReflection {

  #region Descriptor
  /// <summary>File descriptor for ProfileResIdl.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProfileResIdlReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNQcm9maWxlUmVzSWRsLnByb3RvGgtFcnJvci5wcm90bxoKVXNlci5wcm90",
          "bxoSUG9zdEluZm9MaXN0LnByb3RvIuwCCg1Qcm9maWxlUmVzSWRsEhUKBWVy",
          "cm9yGAEgASgLMgYuRXJyb3ISJAoEZGF0YRgCIAEoCzIWLlByb2ZpbGVSZXNJ",
          "ZGwuRGF0YVJlcxqdAgoHRGF0YVJlcxITCgR1c2VyGAEgASgLMgUuVXNlchIu",
          "CglhbnRpX3N0YXQYAiABKAsyGy5Qcm9maWxlUmVzSWRsLkRhdGFSZXMuQW50",
          "aRIgCglwb3N0X2xpc3QYBCADKAsyDS5Qb3N0SW5mb0xpc3QSPQoPdXNlcl9h",
          "Z3JlZV9pbmZvGA4gASgLMiQuUHJvZmlsZVJlc0lkbC5EYXRhUmVzLlVzZXJB",
          "Z3JlZUluZm8aQgoEQW50aRISCgpibG9ja19zdGF0GAYgASgFEhEKCWhpZGVf",
          "c3RhdBgHIAEoBRITCgtkYXlzX3RvZnJlZRgJIAEoBRooCg1Vc2VyQWdyZWVJ",
          "bmZvEhcKD3RvdGFsX2FncmVlX251bRgBIAEoA2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ErrorReflection.Descriptor, global::UserReflection.Descriptor, global::PostInfoListReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProfileResIdl), global::ProfileResIdl.Parser, new[]{ "Error", "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProfileResIdl.Types.DataRes), global::ProfileResIdl.Types.DataRes.Parser, new[]{ "User", "AntiStat", "PostList", "UserAgreeInfo" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProfileResIdl.Types.DataRes.Types.Anti), global::ProfileResIdl.Types.DataRes.Types.Anti.Parser, new[]{ "BlockStat", "HideStat", "DaysTofree" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProfileResIdl.Types.DataRes.Types.UserAgreeInfo), global::ProfileResIdl.Types.DataRes.Types.UserAgreeInfo.Parser, new[]{ "TotalAgreeNum" }, null, null, null, null)})})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ProfileResIdl : pb::IMessage<ProfileResIdl>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProfileResIdl> _parser = new pb::MessageParser<ProfileResIdl>(() => new ProfileResIdl());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProfileResIdl> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProfileResIdlReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProfileResIdl() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProfileResIdl(ProfileResIdl other) : this() {
    error_ = other.error_ != null ? other.error_.Clone() : null;
    data_ = other.data_ != null ? other.data_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProfileResIdl Clone() {
    return new ProfileResIdl(this);
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 1;
  private global::Error error_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Error Error {
    get { return error_; }
    set {
      error_ = value;
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 2;
  private global::ProfileResIdl.Types.DataRes data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProfileResIdl.Types.DataRes Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProfileResIdl);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProfileResIdl other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Error, other.Error)) return false;
    if (!object.Equals(Data, other.Data)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (error_ != null) hash ^= Error.GetHashCode();
    if (data_ != null) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (error_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (error_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (error_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
    }
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProfileResIdl other) {
    if (other == null) {
      return;
    }
    if (other.error_ != null) {
      if (error_ == null) {
        Error = new global::Error();
      }
      Error.MergeFrom(other.Error);
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::ProfileResIdl.Types.DataRes();
      }
      Data.MergeFrom(other.Data);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
        case 18: {
          if (data_ == null) {
            Data = new global::ProfileResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
        case 18: {
          if (data_ == null) {
            Data = new global::ProfileResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the ProfileResIdl message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class DataRes : pb::IMessage<DataRes>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<DataRes> _parser = new pb::MessageParser<DataRes>(() => new DataRes());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<DataRes> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::ProfileResIdl.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes(DataRes other) : this() {
        user_ = other.user_ != null ? other.user_.Clone() : null;
        antiStat_ = other.antiStat_ != null ? other.antiStat_.Clone() : null;
        postList_ = other.postList_.Clone();
        userAgreeInfo_ = other.userAgreeInfo_ != null ? other.userAgreeInfo_.Clone() : null;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes Clone() {
        return new DataRes(this);
      }

      /// <summary>Field number for the "user" field.</summary>
      public const int UserFieldNumber = 1;
      private global::User user_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::User User {
        get { return user_; }
        set {
          user_ = value;
        }
      }

      /// <summary>Field number for the "anti_stat" field.</summary>
      public const int AntiStatFieldNumber = 2;
      private global::ProfileResIdl.Types.DataRes.Types.Anti antiStat_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::ProfileResIdl.Types.DataRes.Types.Anti AntiStat {
        get { return antiStat_; }
        set {
          antiStat_ = value;
        }
      }

      /// <summary>Field number for the "post_list" field.</summary>
      public const int PostListFieldNumber = 4;
      private static readonly pb::FieldCodec<global::PostInfoList> _repeated_postList_codec
          = pb::FieldCodec.ForMessage(34, global::PostInfoList.Parser);
      private readonly pbc::RepeatedField<global::PostInfoList> postList_ = new pbc::RepeatedField<global::PostInfoList>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::PostInfoList> PostList {
        get { return postList_; }
      }

      /// <summary>Field number for the "user_agree_info" field.</summary>
      public const int UserAgreeInfoFieldNumber = 14;
      private global::ProfileResIdl.Types.DataRes.Types.UserAgreeInfo userAgreeInfo_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::ProfileResIdl.Types.DataRes.Types.UserAgreeInfo UserAgreeInfo {
        get { return userAgreeInfo_; }
        set {
          userAgreeInfo_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as DataRes);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(DataRes other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (!object.Equals(User, other.User)) return false;
        if (!object.Equals(AntiStat, other.AntiStat)) return false;
        if(!postList_.Equals(other.postList_)) return false;
        if (!object.Equals(UserAgreeInfo, other.UserAgreeInfo)) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (user_ != null) hash ^= User.GetHashCode();
        if (antiStat_ != null) hash ^= AntiStat.GetHashCode();
        hash ^= postList_.GetHashCode();
        if (userAgreeInfo_ != null) hash ^= UserAgreeInfo.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (user_ != null) {
          output.WriteRawTag(10);
          output.WriteMessage(User);
        }
        if (antiStat_ != null) {
          output.WriteRawTag(18);
          output.WriteMessage(AntiStat);
        }
        postList_.WriteTo(output, _repeated_postList_codec);
        if (userAgreeInfo_ != null) {
          output.WriteRawTag(114);
          output.WriteMessage(UserAgreeInfo);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (user_ != null) {
          output.WriteRawTag(10);
          output.WriteMessage(User);
        }
        if (antiStat_ != null) {
          output.WriteRawTag(18);
          output.WriteMessage(AntiStat);
        }
        postList_.WriteTo(ref output, _repeated_postList_codec);
        if (userAgreeInfo_ != null) {
          output.WriteRawTag(114);
          output.WriteMessage(UserAgreeInfo);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (user_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
        }
        if (antiStat_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(AntiStat);
        }
        size += postList_.CalculateSize(_repeated_postList_codec);
        if (userAgreeInfo_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserAgreeInfo);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(DataRes other) {
        if (other == null) {
          return;
        }
        if (other.user_ != null) {
          if (user_ == null) {
            User = new global::User();
          }
          User.MergeFrom(other.User);
        }
        if (other.antiStat_ != null) {
          if (antiStat_ == null) {
            AntiStat = new global::ProfileResIdl.Types.DataRes.Types.Anti();
          }
          AntiStat.MergeFrom(other.AntiStat);
        }
        postList_.Add(other.postList_);
        if (other.userAgreeInfo_ != null) {
          if (userAgreeInfo_ == null) {
            UserAgreeInfo = new global::ProfileResIdl.Types.DataRes.Types.UserAgreeInfo();
          }
          UserAgreeInfo.MergeFrom(other.UserAgreeInfo);
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              if (user_ == null) {
                User = new global::User();
              }
              input.ReadMessage(User);
              break;
            }
            case 18: {
              if (antiStat_ == null) {
                AntiStat = new global::ProfileResIdl.Types.DataRes.Types.Anti();
              }
              input.ReadMessage(AntiStat);
              break;
            }
            case 34: {
              postList_.AddEntriesFrom(input, _repeated_postList_codec);
              break;
            }
            case 114: {
              if (userAgreeInfo_ == null) {
                UserAgreeInfo = new global::ProfileResIdl.Types.DataRes.Types.UserAgreeInfo();
              }
              input.ReadMessage(UserAgreeInfo);
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              if (user_ == null) {
                User = new global::User();
              }
              input.ReadMessage(User);
              break;
            }
            case 18: {
              if (antiStat_ == null) {
                AntiStat = new global::ProfileResIdl.Types.DataRes.Types.Anti();
              }
              input.ReadMessage(AntiStat);
              break;
            }
            case 34: {
              postList_.AddEntriesFrom(ref input, _repeated_postList_codec);
              break;
            }
            case 114: {
              if (userAgreeInfo_ == null) {
                UserAgreeInfo = new global::ProfileResIdl.Types.DataRes.Types.UserAgreeInfo();
              }
              input.ReadMessage(UserAgreeInfo);
              break;
            }
          }
        }
      }
      #endif

      #region Nested types
      /// <summary>Container for nested types declared in the DataRes message type.</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static partial class Types {
        [global::System.SerializableAttribute]
        [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
        public sealed partial class Anti : pb::IMessage<Anti>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<Anti> _parser = new pb::MessageParser<Anti>(() => new Anti());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pb::MessageParser<Anti> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::ProfileResIdl.Types.DataRes.Descriptor.NestedTypes[0]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Anti() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Anti(Anti other) : this() {
            blockStat_ = other.blockStat_;
            hideStat_ = other.hideStat_;
            daysTofree_ = other.daysTofree_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Anti Clone() {
            return new Anti(this);
          }

          /// <summary>Field number for the "block_stat" field.</summary>
          public const int BlockStatFieldNumber = 6;
          private int blockStat_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int BlockStat {
            get { return blockStat_; }
            set {
              blockStat_ = value;
            }
          }

          /// <summary>Field number for the "hide_stat" field.</summary>
          public const int HideStatFieldNumber = 7;
          private int hideStat_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int HideStat {
            get { return hideStat_; }
            set {
              hideStat_ = value;
            }
          }

          /// <summary>Field number for the "days_tofree" field.</summary>
          public const int DaysTofreeFieldNumber = 9;
          private int daysTofree_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int DaysTofree {
            get { return daysTofree_; }
            set {
              daysTofree_ = value;
            }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override bool Equals(object other) {
            return Equals(other as Anti);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool Equals(Anti other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (BlockStat != other.BlockStat) return false;
            if (HideStat != other.HideStat) return false;
            if (DaysTofree != other.DaysTofree) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override int GetHashCode() {
            int hash = 1;
            if (BlockStat != 0) hash ^= BlockStat.GetHashCode();
            if (HideStat != 0) hash ^= HideStat.GetHashCode();
            if (DaysTofree != 0) hash ^= DaysTofree.GetHashCode();
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (BlockStat != 0) {
              output.WriteRawTag(48);
              output.WriteInt32(BlockStat);
            }
            if (HideStat != 0) {
              output.WriteRawTag(56);
              output.WriteInt32(HideStat);
            }
            if (DaysTofree != 0) {
              output.WriteRawTag(72);
              output.WriteInt32(DaysTofree);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (BlockStat != 0) {
              output.WriteRawTag(48);
              output.WriteInt32(BlockStat);
            }
            if (HideStat != 0) {
              output.WriteRawTag(56);
              output.WriteInt32(HideStat);
            }
            if (DaysTofree != 0) {
              output.WriteRawTag(72);
              output.WriteInt32(DaysTofree);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int CalculateSize() {
            int size = 0;
            if (BlockStat != 0) {
              size += 1 + pb::CodedOutputStream.ComputeInt32Size(BlockStat);
            }
            if (HideStat != 0) {
              size += 1 + pb::CodedOutputStream.ComputeInt32Size(HideStat);
            }
            if (DaysTofree != 0) {
              size += 1 + pb::CodedOutputStream.ComputeInt32Size(DaysTofree);
            }
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(Anti other) {
            if (other == null) {
              return;
            }
            if (other.BlockStat != 0) {
              BlockStat = other.BlockStat;
            }
            if (other.HideStat != 0) {
              HideStat = other.HideStat;
            }
            if (other.DaysTofree != 0) {
              DaysTofree = other.DaysTofree;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 48: {
                  BlockStat = input.ReadInt32();
                  break;
                }
                case 56: {
                  HideStat = input.ReadInt32();
                  break;
                }
                case 72: {
                  DaysTofree = input.ReadInt32();
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 48: {
                  BlockStat = input.ReadInt32();
                  break;
                }
                case 56: {
                  HideStat = input.ReadInt32();
                  break;
                }
                case 72: {
                  DaysTofree = input.ReadInt32();
                  break;
                }
              }
            }
          }
          #endif

        }

        [global::System.SerializableAttribute]
        [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
        public sealed partial class UserAgreeInfo : pb::IMessage<UserAgreeInfo>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<UserAgreeInfo> _parser = new pb::MessageParser<UserAgreeInfo>(() => new UserAgreeInfo());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pb::MessageParser<UserAgreeInfo> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::ProfileResIdl.Types.DataRes.Descriptor.NestedTypes[1]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public UserAgreeInfo() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public UserAgreeInfo(UserAgreeInfo other) : this() {
            totalAgreeNum_ = other.totalAgreeNum_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public UserAgreeInfo Clone() {
            return new UserAgreeInfo(this);
          }

          /// <summary>Field number for the "total_agree_num" field.</summary>
          public const int TotalAgreeNumFieldNumber = 1;
          private long totalAgreeNum_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public long TotalAgreeNum {
            get { return totalAgreeNum_; }
            set {
              totalAgreeNum_ = value;
            }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override bool Equals(object other) {
            return Equals(other as UserAgreeInfo);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool Equals(UserAgreeInfo other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (TotalAgreeNum != other.TotalAgreeNum) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override int GetHashCode() {
            int hash = 1;
            if (TotalAgreeNum != 0L) hash ^= TotalAgreeNum.GetHashCode();
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (TotalAgreeNum != 0L) {
              output.WriteRawTag(8);
              output.WriteInt64(TotalAgreeNum);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (TotalAgreeNum != 0L) {
              output.WriteRawTag(8);
              output.WriteInt64(TotalAgreeNum);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int CalculateSize() {
            int size = 0;
            if (TotalAgreeNum != 0L) {
              size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalAgreeNum);
            }
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(UserAgreeInfo other) {
            if (other == null) {
              return;
            }
            if (other.TotalAgreeNum != 0L) {
              TotalAgreeNum = other.TotalAgreeNum;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 8: {
                  TotalAgreeNum = input.ReadInt64();
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 8: {
                  TotalAgreeNum = input.ReadInt64();
                  break;
                }
              }
            }
          }
          #endif

        }

      }
      #endregion

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
