// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PostInfoList.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PostInfoList.proto</summary>
public static partial class PostInfoListReflection {

  #region Descriptor
  /// <summary>File descriptor for PostInfoList.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PostInfoListReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJQb3N0SW5mb0xpc3QucHJvdG8aC01lZGlhLnByb3RvGgtWb2ljZS5wcm90",
          "bxoOUG9sbEluZm8ucHJvdG8aD1ZpZGVvSW5mby5wcm90bxoPUGJDb250ZW50",
          "LnByb3RvGgtBZ3JlZS5wcm90byL5BQoMUG9zdEluZm9MaXN0EhAKCGZvcnVt",
          "X2lkGAEgASgEEhEKCXRocmVhZF9pZBgCIAEoBBIPCgdwb3N0X2lkGAMgASgE",
          "EhMKC2NyZWF0ZV90aW1lGAUgASgNEhIKCmZvcnVtX25hbWUYBiABKAkSDQoF",
          "dGl0bGUYByABKAkSLgoHY29udGVudBgIIAMoCzIdLlBvc3RJbmZvTGlzdC5Q",
          "b3N0SW5mb0NvbnRlbnQSEQoJdXNlcl9uYW1lGAogASgJEhUKBW1lZGlhGBAg",
          "AygLMgYuTWVkaWESEQoJcmVwbHlfbnVtGBEgASgNEg8KB3VzZXJfaWQYEiAB",
          "KAMSFQoNdXNlcl9wb3J0cmFpdBgTIAEoCRIaCgp2b2ljZV9pbmZvGBcgAygL",
          "MgYuVm9pY2USEwoLdGhyZWFkX3R5cGUYGiABKAQSHAoJcG9sbF9pbmZvGBwg",
          "ASgLMgkuUG9sbEluZm8SHgoKdmlkZW9faW5mbxgdIAEoCzIKLlZpZGVvSW5m",
          "bxIQCghmcmVxX251bRghIAEoBRIRCgluYW1lX3Nob3cYIyABKAkSEQoJc2hh",
          "cmVfbnVtGCcgASgFEhUKBWFncmVlGCggASgLMgYuQWdyZWUSFwoPaXNfc2hh",
          "cmVfdGhyZWFkGCwgASgFEiYKEmZpcnN0X3Bvc3RfY29udGVudBgxIAMoCzIK",
          "LlBiQ29udGVudBrmAQoPUG9zdEluZm9Db250ZW50EjwKDHBvc3RfY29udGVu",
          "dBgBIAMoCzImLlBvc3RJbmZvTGlzdC5Qb3N0SW5mb0NvbnRlbnQuQWJzdHJh",
          "Y3QSEwoLY3JlYXRlX3RpbWUYAiABKAQSEQoJcG9zdF90eXBlGAMgASgEEg8K",
          "B3Bvc3RfaWQYBCABKAQaXAoIQWJzdHJhY3QSDAoEdHlwZRgBIAEoBRIMCgR0",
          "ZXh0GAIgASgJEgwKBGxpbmsYAyABKAkSEwoLZHVyaW5nX3RpbWUYBiABKAkS",
          "EQoJdm9pY2VfbWQ1GAcgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::MediaReflection.Descriptor, global::VoiceReflection.Descriptor, global::PollInfoReflection.Descriptor, global::VideoInfoReflection.Descriptor, global::PbContentReflection.Descriptor, global::AgreeReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PostInfoList), global::PostInfoList.Parser, new[]{ "ForumId", "ThreadId", "PostId", "CreateTime", "ForumName", "Title", "Content", "UserName", "Media", "ReplyNum", "UserId", "UserPortrait", "VoiceInfo", "ThreadType", "PollInfo", "VideoInfo", "FreqNum", "NameShow", "ShareNum", "Agree", "IsShareThread", "FirstPostContent" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PostInfoList.Types.PostInfoContent), global::PostInfoList.Types.PostInfoContent.Parser, new[]{ "PostContent", "CreateTime", "PostType", "PostId" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PostInfoList.Types.PostInfoContent.Types.Abstract), global::PostInfoList.Types.PostInfoContent.Types.Abstract.Parser, new[]{ "Type", "Text", "Link", "DuringTime", "VoiceMd5" }, null, null, null, null)})})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PostInfoList : pb::IMessage<PostInfoList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PostInfoList> _parser = new pb::MessageParser<PostInfoList>(() => new PostInfoList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PostInfoList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PostInfoListReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PostInfoList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PostInfoList(PostInfoList other) : this() {
    forumId_ = other.forumId_;
    threadId_ = other.threadId_;
    postId_ = other.postId_;
    createTime_ = other.createTime_;
    forumName_ = other.forumName_;
    title_ = other.title_;
    content_ = other.content_.Clone();
    userName_ = other.userName_;
    media_ = other.media_.Clone();
    replyNum_ = other.replyNum_;
    userId_ = other.userId_;
    userPortrait_ = other.userPortrait_;
    voiceInfo_ = other.voiceInfo_.Clone();
    threadType_ = other.threadType_;
    pollInfo_ = other.pollInfo_ != null ? other.pollInfo_.Clone() : null;
    videoInfo_ = other.videoInfo_ != null ? other.videoInfo_.Clone() : null;
    freqNum_ = other.freqNum_;
    nameShow_ = other.nameShow_;
    shareNum_ = other.shareNum_;
    agree_ = other.agree_ != null ? other.agree_.Clone() : null;
    isShareThread_ = other.isShareThread_;
    firstPostContent_ = other.firstPostContent_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PostInfoList Clone() {
    return new PostInfoList(this);
  }

  /// <summary>Field number for the "forum_id" field.</summary>
  public const int ForumIdFieldNumber = 1;
  private ulong forumId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong ForumId {
    get { return forumId_; }
    set {
      forumId_ = value;
    }
  }

  /// <summary>Field number for the "thread_id" field.</summary>
  public const int ThreadIdFieldNumber = 2;
  private ulong threadId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong ThreadId {
    get { return threadId_; }
    set {
      threadId_ = value;
    }
  }

  /// <summary>Field number for the "post_id" field.</summary>
  public const int PostIdFieldNumber = 3;
  private ulong postId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong PostId {
    get { return postId_; }
    set {
      postId_ = value;
    }
  }

  /// <summary>Field number for the "create_time" field.</summary>
  public const int CreateTimeFieldNumber = 5;
  private uint createTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CreateTime {
    get { return createTime_; }
    set {
      createTime_ = value;
    }
  }

  /// <summary>Field number for the "forum_name" field.</summary>
  public const int ForumNameFieldNumber = 6;
  private string forumName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ForumName {
    get { return forumName_; }
    set {
      forumName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "title" field.</summary>
  public const int TitleFieldNumber = 7;
  private string title_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Title {
    get { return title_; }
    set {
      title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "content" field.</summary>
  public const int ContentFieldNumber = 8;
  private static readonly pb::FieldCodec<global::PostInfoList.Types.PostInfoContent> _repeated_content_codec
      = pb::FieldCodec.ForMessage(66, global::PostInfoList.Types.PostInfoContent.Parser);
  private readonly pbc::RepeatedField<global::PostInfoList.Types.PostInfoContent> content_ = new pbc::RepeatedField<global::PostInfoList.Types.PostInfoContent>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::PostInfoList.Types.PostInfoContent> Content {
    get { return content_; }
  }

  /// <summary>Field number for the "user_name" field.</summary>
  public const int UserNameFieldNumber = 10;
  private string userName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserName {
    get { return userName_; }
    set {
      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "media" field.</summary>
  public const int MediaFieldNumber = 16;
  private static readonly pb::FieldCodec<global::Media> _repeated_media_codec
      = pb::FieldCodec.ForMessage(130, global::Media.Parser);
  private readonly pbc::RepeatedField<global::Media> media_ = new pbc::RepeatedField<global::Media>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Media> Media {
    get { return media_; }
  }

  /// <summary>Field number for the "reply_num" field.</summary>
  public const int ReplyNumFieldNumber = 17;
  private uint replyNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ReplyNum {
    get { return replyNum_; }
    set {
      replyNum_ = value;
    }
  }

  /// <summary>Field number for the "user_id" field.</summary>
  public const int UserIdFieldNumber = 18;
  private long userId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  /// <summary>Field number for the "user_portrait" field.</summary>
  public const int UserPortraitFieldNumber = 19;
  private string userPortrait_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserPortrait {
    get { return userPortrait_; }
    set {
      userPortrait_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "voice_info" field.</summary>
  public const int VoiceInfoFieldNumber = 23;
  private static readonly pb::FieldCodec<global::Voice> _repeated_voiceInfo_codec
      = pb::FieldCodec.ForMessage(186, global::Voice.Parser);
  private readonly pbc::RepeatedField<global::Voice> voiceInfo_ = new pbc::RepeatedField<global::Voice>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Voice> VoiceInfo {
    get { return voiceInfo_; }
  }

  /// <summary>Field number for the "thread_type" field.</summary>
  public const int ThreadTypeFieldNumber = 26;
  private ulong threadType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong ThreadType {
    get { return threadType_; }
    set {
      threadType_ = value;
    }
  }

  /// <summary>Field number for the "poll_info" field.</summary>
  public const int PollInfoFieldNumber = 28;
  private global::PollInfo pollInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PollInfo PollInfo {
    get { return pollInfo_; }
    set {
      pollInfo_ = value;
    }
  }

  /// <summary>Field number for the "video_info" field.</summary>
  public const int VideoInfoFieldNumber = 29;
  private global::VideoInfo videoInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::VideoInfo VideoInfo {
    get { return videoInfo_; }
    set {
      videoInfo_ = value;
    }
  }

  /// <summary>Field number for the "freq_num" field.</summary>
  public const int FreqNumFieldNumber = 33;
  private int freqNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int FreqNum {
    get { return freqNum_; }
    set {
      freqNum_ = value;
    }
  }

  /// <summary>Field number for the "name_show" field.</summary>
  public const int NameShowFieldNumber = 35;
  private string nameShow_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NameShow {
    get { return nameShow_; }
    set {
      nameShow_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "share_num" field.</summary>
  public const int ShareNumFieldNumber = 39;
  private int shareNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ShareNum {
    get { return shareNum_; }
    set {
      shareNum_ = value;
    }
  }

  /// <summary>Field number for the "agree" field.</summary>
  public const int AgreeFieldNumber = 40;
  private global::Agree agree_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Agree Agree {
    get { return agree_; }
    set {
      agree_ = value;
    }
  }

  /// <summary>Field number for the "is_share_thread" field.</summary>
  public const int IsShareThreadFieldNumber = 44;
  private int isShareThread_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsShareThread {
    get { return isShareThread_; }
    set {
      isShareThread_ = value;
    }
  }

  /// <summary>Field number for the "first_post_content" field.</summary>
  public const int FirstPostContentFieldNumber = 49;
  private static readonly pb::FieldCodec<global::PbContent> _repeated_firstPostContent_codec
      = pb::FieldCodec.ForMessage(394, global::PbContent.Parser);
  private readonly pbc::RepeatedField<global::PbContent> firstPostContent_ = new pbc::RepeatedField<global::PbContent>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::PbContent> FirstPostContent {
    get { return firstPostContent_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PostInfoList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PostInfoList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ForumId != other.ForumId) return false;
    if (ThreadId != other.ThreadId) return false;
    if (PostId != other.PostId) return false;
    if (CreateTime != other.CreateTime) return false;
    if (ForumName != other.ForumName) return false;
    if (Title != other.Title) return false;
    if(!content_.Equals(other.content_)) return false;
    if (UserName != other.UserName) return false;
    if(!media_.Equals(other.media_)) return false;
    if (ReplyNum != other.ReplyNum) return false;
    if (UserId != other.UserId) return false;
    if (UserPortrait != other.UserPortrait) return false;
    if(!voiceInfo_.Equals(other.voiceInfo_)) return false;
    if (ThreadType != other.ThreadType) return false;
    if (!object.Equals(PollInfo, other.PollInfo)) return false;
    if (!object.Equals(VideoInfo, other.VideoInfo)) return false;
    if (FreqNum != other.FreqNum) return false;
    if (NameShow != other.NameShow) return false;
    if (ShareNum != other.ShareNum) return false;
    if (!object.Equals(Agree, other.Agree)) return false;
    if (IsShareThread != other.IsShareThread) return false;
    if(!firstPostContent_.Equals(other.firstPostContent_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ForumId != 0UL) hash ^= ForumId.GetHashCode();
    if (ThreadId != 0UL) hash ^= ThreadId.GetHashCode();
    if (PostId != 0UL) hash ^= PostId.GetHashCode();
    if (CreateTime != 0) hash ^= CreateTime.GetHashCode();
    if (ForumName.Length != 0) hash ^= ForumName.GetHashCode();
    if (Title.Length != 0) hash ^= Title.GetHashCode();
    hash ^= content_.GetHashCode();
    if (UserName.Length != 0) hash ^= UserName.GetHashCode();
    hash ^= media_.GetHashCode();
    if (ReplyNum != 0) hash ^= ReplyNum.GetHashCode();
    if (UserId != 0L) hash ^= UserId.GetHashCode();
    if (UserPortrait.Length != 0) hash ^= UserPortrait.GetHashCode();
    hash ^= voiceInfo_.GetHashCode();
    if (ThreadType != 0UL) hash ^= ThreadType.GetHashCode();
    if (pollInfo_ != null) hash ^= PollInfo.GetHashCode();
    if (videoInfo_ != null) hash ^= VideoInfo.GetHashCode();
    if (FreqNum != 0) hash ^= FreqNum.GetHashCode();
    if (NameShow.Length != 0) hash ^= NameShow.GetHashCode();
    if (ShareNum != 0) hash ^= ShareNum.GetHashCode();
    if (agree_ != null) hash ^= Agree.GetHashCode();
    if (IsShareThread != 0) hash ^= IsShareThread.GetHashCode();
    hash ^= firstPostContent_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ForumId != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(ForumId);
    }
    if (ThreadId != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(ThreadId);
    }
    if (PostId != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(PostId);
    }
    if (CreateTime != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(CreateTime);
    }
    if (ForumName.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(ForumName);
    }
    if (Title.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Title);
    }
    content_.WriteTo(output, _repeated_content_codec);
    if (UserName.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(UserName);
    }
    media_.WriteTo(output, _repeated_media_codec);
    if (ReplyNum != 0) {
      output.WriteRawTag(136, 1);
      output.WriteUInt32(ReplyNum);
    }
    if (UserId != 0L) {
      output.WriteRawTag(144, 1);
      output.WriteInt64(UserId);
    }
    if (UserPortrait.Length != 0) {
      output.WriteRawTag(154, 1);
      output.WriteString(UserPortrait);
    }
    voiceInfo_.WriteTo(output, _repeated_voiceInfo_codec);
    if (ThreadType != 0UL) {
      output.WriteRawTag(208, 1);
      output.WriteUInt64(ThreadType);
    }
    if (pollInfo_ != null) {
      output.WriteRawTag(226, 1);
      output.WriteMessage(PollInfo);
    }
    if (videoInfo_ != null) {
      output.WriteRawTag(234, 1);
      output.WriteMessage(VideoInfo);
    }
    if (FreqNum != 0) {
      output.WriteRawTag(136, 2);
      output.WriteInt32(FreqNum);
    }
    if (NameShow.Length != 0) {
      output.WriteRawTag(154, 2);
      output.WriteString(NameShow);
    }
    if (ShareNum != 0) {
      output.WriteRawTag(184, 2);
      output.WriteInt32(ShareNum);
    }
    if (agree_ != null) {
      output.WriteRawTag(194, 2);
      output.WriteMessage(Agree);
    }
    if (IsShareThread != 0) {
      output.WriteRawTag(224, 2);
      output.WriteInt32(IsShareThread);
    }
    firstPostContent_.WriteTo(output, _repeated_firstPostContent_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ForumId != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(ForumId);
    }
    if (ThreadId != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(ThreadId);
    }
    if (PostId != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(PostId);
    }
    if (CreateTime != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(CreateTime);
    }
    if (ForumName.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(ForumName);
    }
    if (Title.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Title);
    }
    content_.WriteTo(ref output, _repeated_content_codec);
    if (UserName.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(UserName);
    }
    media_.WriteTo(ref output, _repeated_media_codec);
    if (ReplyNum != 0) {
      output.WriteRawTag(136, 1);
      output.WriteUInt32(ReplyNum);
    }
    if (UserId != 0L) {
      output.WriteRawTag(144, 1);
      output.WriteInt64(UserId);
    }
    if (UserPortrait.Length != 0) {
      output.WriteRawTag(154, 1);
      output.WriteString(UserPortrait);
    }
    voiceInfo_.WriteTo(ref output, _repeated_voiceInfo_codec);
    if (ThreadType != 0UL) {
      output.WriteRawTag(208, 1);
      output.WriteUInt64(ThreadType);
    }
    if (pollInfo_ != null) {
      output.WriteRawTag(226, 1);
      output.WriteMessage(PollInfo);
    }
    if (videoInfo_ != null) {
      output.WriteRawTag(234, 1);
      output.WriteMessage(VideoInfo);
    }
    if (FreqNum != 0) {
      output.WriteRawTag(136, 2);
      output.WriteInt32(FreqNum);
    }
    if (NameShow.Length != 0) {
      output.WriteRawTag(154, 2);
      output.WriteString(NameShow);
    }
    if (ShareNum != 0) {
      output.WriteRawTag(184, 2);
      output.WriteInt32(ShareNum);
    }
    if (agree_ != null) {
      output.WriteRawTag(194, 2);
      output.WriteMessage(Agree);
    }
    if (IsShareThread != 0) {
      output.WriteRawTag(224, 2);
      output.WriteInt32(IsShareThread);
    }
    firstPostContent_.WriteTo(ref output, _repeated_firstPostContent_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ForumId != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ForumId);
    }
    if (ThreadId != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ThreadId);
    }
    if (PostId != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PostId);
    }
    if (CreateTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CreateTime);
    }
    if (ForumName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ForumName);
    }
    if (Title.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
    }
    size += content_.CalculateSize(_repeated_content_codec);
    if (UserName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
    }
    size += media_.CalculateSize(_repeated_media_codec);
    if (ReplyNum != 0) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(ReplyNum);
    }
    if (UserId != 0L) {
      size += 2 + pb::CodedOutputStream.ComputeInt64Size(UserId);
    }
    if (UserPortrait.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(UserPortrait);
    }
    size += voiceInfo_.CalculateSize(_repeated_voiceInfo_codec);
    if (ThreadType != 0UL) {
      size += 2 + pb::CodedOutputStream.ComputeUInt64Size(ThreadType);
    }
    if (pollInfo_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(PollInfo);
    }
    if (videoInfo_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(VideoInfo);
    }
    if (FreqNum != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(FreqNum);
    }
    if (NameShow.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(NameShow);
    }
    if (ShareNum != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(ShareNum);
    }
    if (agree_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Agree);
    }
    if (IsShareThread != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IsShareThread);
    }
    size += firstPostContent_.CalculateSize(_repeated_firstPostContent_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PostInfoList other) {
    if (other == null) {
      return;
    }
    if (other.ForumId != 0UL) {
      ForumId = other.ForumId;
    }
    if (other.ThreadId != 0UL) {
      ThreadId = other.ThreadId;
    }
    if (other.PostId != 0UL) {
      PostId = other.PostId;
    }
    if (other.CreateTime != 0) {
      CreateTime = other.CreateTime;
    }
    if (other.ForumName.Length != 0) {
      ForumName = other.ForumName;
    }
    if (other.Title.Length != 0) {
      Title = other.Title;
    }
    content_.Add(other.content_);
    if (other.UserName.Length != 0) {
      UserName = other.UserName;
    }
    media_.Add(other.media_);
    if (other.ReplyNum != 0) {
      ReplyNum = other.ReplyNum;
    }
    if (other.UserId != 0L) {
      UserId = other.UserId;
    }
    if (other.UserPortrait.Length != 0) {
      UserPortrait = other.UserPortrait;
    }
    voiceInfo_.Add(other.voiceInfo_);
    if (other.ThreadType != 0UL) {
      ThreadType = other.ThreadType;
    }
    if (other.pollInfo_ != null) {
      if (pollInfo_ == null) {
        PollInfo = new global::PollInfo();
      }
      PollInfo.MergeFrom(other.PollInfo);
    }
    if (other.videoInfo_ != null) {
      if (videoInfo_ == null) {
        VideoInfo = new global::VideoInfo();
      }
      VideoInfo.MergeFrom(other.VideoInfo);
    }
    if (other.FreqNum != 0) {
      FreqNum = other.FreqNum;
    }
    if (other.NameShow.Length != 0) {
      NameShow = other.NameShow;
    }
    if (other.ShareNum != 0) {
      ShareNum = other.ShareNum;
    }
    if (other.agree_ != null) {
      if (agree_ == null) {
        Agree = new global::Agree();
      }
      Agree.MergeFrom(other.Agree);
    }
    if (other.IsShareThread != 0) {
      IsShareThread = other.IsShareThread;
    }
    firstPostContent_.Add(other.firstPostContent_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ForumId = input.ReadUInt64();
          break;
        }
        case 16: {
          ThreadId = input.ReadUInt64();
          break;
        }
        case 24: {
          PostId = input.ReadUInt64();
          break;
        }
        case 40: {
          CreateTime = input.ReadUInt32();
          break;
        }
        case 50: {
          ForumName = input.ReadString();
          break;
        }
        case 58: {
          Title = input.ReadString();
          break;
        }
        case 66: {
          content_.AddEntriesFrom(input, _repeated_content_codec);
          break;
        }
        case 82: {
          UserName = input.ReadString();
          break;
        }
        case 130: {
          media_.AddEntriesFrom(input, _repeated_media_codec);
          break;
        }
        case 136: {
          ReplyNum = input.ReadUInt32();
          break;
        }
        case 144: {
          UserId = input.ReadInt64();
          break;
        }
        case 154: {
          UserPortrait = input.ReadString();
          break;
        }
        case 186: {
          voiceInfo_.AddEntriesFrom(input, _repeated_voiceInfo_codec);
          break;
        }
        case 208: {
          ThreadType = input.ReadUInt64();
          break;
        }
        case 226: {
          if (pollInfo_ == null) {
            PollInfo = new global::PollInfo();
          }
          input.ReadMessage(PollInfo);
          break;
        }
        case 234: {
          if (videoInfo_ == null) {
            VideoInfo = new global::VideoInfo();
          }
          input.ReadMessage(VideoInfo);
          break;
        }
        case 264: {
          FreqNum = input.ReadInt32();
          break;
        }
        case 282: {
          NameShow = input.ReadString();
          break;
        }
        case 312: {
          ShareNum = input.ReadInt32();
          break;
        }
        case 322: {
          if (agree_ == null) {
            Agree = new global::Agree();
          }
          input.ReadMessage(Agree);
          break;
        }
        case 352: {
          IsShareThread = input.ReadInt32();
          break;
        }
        case 394: {
          firstPostContent_.AddEntriesFrom(input, _repeated_firstPostContent_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ForumId = input.ReadUInt64();
          break;
        }
        case 16: {
          ThreadId = input.ReadUInt64();
          break;
        }
        case 24: {
          PostId = input.ReadUInt64();
          break;
        }
        case 40: {
          CreateTime = input.ReadUInt32();
          break;
        }
        case 50: {
          ForumName = input.ReadString();
          break;
        }
        case 58: {
          Title = input.ReadString();
          break;
        }
        case 66: {
          content_.AddEntriesFrom(ref input, _repeated_content_codec);
          break;
        }
        case 82: {
          UserName = input.ReadString();
          break;
        }
        case 130: {
          media_.AddEntriesFrom(ref input, _repeated_media_codec);
          break;
        }
        case 136: {
          ReplyNum = input.ReadUInt32();
          break;
        }
        case 144: {
          UserId = input.ReadInt64();
          break;
        }
        case 154: {
          UserPortrait = input.ReadString();
          break;
        }
        case 186: {
          voiceInfo_.AddEntriesFrom(ref input, _repeated_voiceInfo_codec);
          break;
        }
        case 208: {
          ThreadType = input.ReadUInt64();
          break;
        }
        case 226: {
          if (pollInfo_ == null) {
            PollInfo = new global::PollInfo();
          }
          input.ReadMessage(PollInfo);
          break;
        }
        case 234: {
          if (videoInfo_ == null) {
            VideoInfo = new global::VideoInfo();
          }
          input.ReadMessage(VideoInfo);
          break;
        }
        case 264: {
          FreqNum = input.ReadInt32();
          break;
        }
        case 282: {
          NameShow = input.ReadString();
          break;
        }
        case 312: {
          ShareNum = input.ReadInt32();
          break;
        }
        case 322: {
          if (agree_ == null) {
            Agree = new global::Agree();
          }
          input.ReadMessage(Agree);
          break;
        }
        case 352: {
          IsShareThread = input.ReadInt32();
          break;
        }
        case 394: {
          firstPostContent_.AddEntriesFrom(ref input, _repeated_firstPostContent_codec);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the PostInfoList message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class PostInfoContent : pb::IMessage<PostInfoContent>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<PostInfoContent> _parser = new pb::MessageParser<PostInfoContent>(() => new PostInfoContent());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<PostInfoContent> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::PostInfoList.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public PostInfoContent() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public PostInfoContent(PostInfoContent other) : this() {
        postContent_ = other.postContent_.Clone();
        createTime_ = other.createTime_;
        postType_ = other.postType_;
        postId_ = other.postId_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public PostInfoContent Clone() {
        return new PostInfoContent(this);
      }

      /// <summary>Field number for the "post_content" field.</summary>
      public const int PostContentFieldNumber = 1;
      private static readonly pb::FieldCodec<global::PostInfoList.Types.PostInfoContent.Types.Abstract> _repeated_postContent_codec
          = pb::FieldCodec.ForMessage(10, global::PostInfoList.Types.PostInfoContent.Types.Abstract.Parser);
      private readonly pbc::RepeatedField<global::PostInfoList.Types.PostInfoContent.Types.Abstract> postContent_ = new pbc::RepeatedField<global::PostInfoList.Types.PostInfoContent.Types.Abstract>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::PostInfoList.Types.PostInfoContent.Types.Abstract> PostContent {
        get { return postContent_; }
      }

      /// <summary>Field number for the "create_time" field.</summary>
      public const int CreateTimeFieldNumber = 2;
      private ulong createTime_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ulong CreateTime {
        get { return createTime_; }
        set {
          createTime_ = value;
        }
      }

      /// <summary>Field number for the "post_type" field.</summary>
      public const int PostTypeFieldNumber = 3;
      private ulong postType_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ulong PostType {
        get { return postType_; }
        set {
          postType_ = value;
        }
      }

      /// <summary>Field number for the "post_id" field.</summary>
      public const int PostIdFieldNumber = 4;
      private ulong postId_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ulong PostId {
        get { return postId_; }
        set {
          postId_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as PostInfoContent);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(PostInfoContent other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if(!postContent_.Equals(other.postContent_)) return false;
        if (CreateTime != other.CreateTime) return false;
        if (PostType != other.PostType) return false;
        if (PostId != other.PostId) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        hash ^= postContent_.GetHashCode();
        if (CreateTime != 0UL) hash ^= CreateTime.GetHashCode();
        if (PostType != 0UL) hash ^= PostType.GetHashCode();
        if (PostId != 0UL) hash ^= PostId.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        postContent_.WriteTo(output, _repeated_postContent_codec);
        if (CreateTime != 0UL) {
          output.WriteRawTag(16);
          output.WriteUInt64(CreateTime);
        }
        if (PostType != 0UL) {
          output.WriteRawTag(24);
          output.WriteUInt64(PostType);
        }
        if (PostId != 0UL) {
          output.WriteRawTag(32);
          output.WriteUInt64(PostId);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        postContent_.WriteTo(ref output, _repeated_postContent_codec);
        if (CreateTime != 0UL) {
          output.WriteRawTag(16);
          output.WriteUInt64(CreateTime);
        }
        if (PostType != 0UL) {
          output.WriteRawTag(24);
          output.WriteUInt64(PostType);
        }
        if (PostId != 0UL) {
          output.WriteRawTag(32);
          output.WriteUInt64(PostId);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        size += postContent_.CalculateSize(_repeated_postContent_codec);
        if (CreateTime != 0UL) {
          size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CreateTime);
        }
        if (PostType != 0UL) {
          size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PostType);
        }
        if (PostId != 0UL) {
          size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PostId);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(PostInfoContent other) {
        if (other == null) {
          return;
        }
        postContent_.Add(other.postContent_);
        if (other.CreateTime != 0UL) {
          CreateTime = other.CreateTime;
        }
        if (other.PostType != 0UL) {
          PostType = other.PostType;
        }
        if (other.PostId != 0UL) {
          PostId = other.PostId;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              postContent_.AddEntriesFrom(input, _repeated_postContent_codec);
              break;
            }
            case 16: {
              CreateTime = input.ReadUInt64();
              break;
            }
            case 24: {
              PostType = input.ReadUInt64();
              break;
            }
            case 32: {
              PostId = input.ReadUInt64();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              postContent_.AddEntriesFrom(ref input, _repeated_postContent_codec);
              break;
            }
            case 16: {
              CreateTime = input.ReadUInt64();
              break;
            }
            case 24: {
              PostType = input.ReadUInt64();
              break;
            }
            case 32: {
              PostId = input.ReadUInt64();
              break;
            }
          }
        }
      }
      #endif

      #region Nested types
      /// <summary>Container for nested types declared in the PostInfoContent message type.</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static partial class Types {
        [global::System.SerializableAttribute]
        [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
        public sealed partial class Abstract : pb::IMessage<Abstract>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<Abstract> _parser = new pb::MessageParser<Abstract>(() => new Abstract());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pb::MessageParser<Abstract> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::PostInfoList.Types.PostInfoContent.Descriptor.NestedTypes[0]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Abstract() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Abstract(Abstract other) : this() {
            type_ = other.type_;
            text_ = other.text_;
            link_ = other.link_;
            duringTime_ = other.duringTime_;
            voiceMd5_ = other.voiceMd5_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Abstract Clone() {
            return new Abstract(this);
          }

          /// <summary>Field number for the "type" field.</summary>
          public const int TypeFieldNumber = 1;
          private int type_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int Type {
            get { return type_; }
            set {
              type_ = value;
            }
          }

          /// <summary>Field number for the "text" field.</summary>
          public const int TextFieldNumber = 2;
          private string text_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string Text {
            get { return text_; }
            set {
              text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "link" field.</summary>
          public const int LinkFieldNumber = 3;
          private string link_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string Link {
            get { return link_; }
            set {
              link_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "during_time" field.</summary>
          public const int DuringTimeFieldNumber = 6;
          private string duringTime_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string DuringTime {
            get { return duringTime_; }
            set {
              duringTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "voice_md5" field.</summary>
          public const int VoiceMd5FieldNumber = 7;
          private string voiceMd5_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string VoiceMd5 {
            get { return voiceMd5_; }
            set {
              voiceMd5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override bool Equals(object other) {
            return Equals(other as Abstract);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool Equals(Abstract other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (Type != other.Type) return false;
            if (Text != other.Text) return false;
            if (Link != other.Link) return false;
            if (DuringTime != other.DuringTime) return false;
            if (VoiceMd5 != other.VoiceMd5) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override int GetHashCode() {
            int hash = 1;
            if (Type != 0) hash ^= Type.GetHashCode();
            if (Text.Length != 0) hash ^= Text.GetHashCode();
            if (Link.Length != 0) hash ^= Link.GetHashCode();
            if (DuringTime.Length != 0) hash ^= DuringTime.GetHashCode();
            if (VoiceMd5.Length != 0) hash ^= VoiceMd5.GetHashCode();
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (Type != 0) {
              output.WriteRawTag(8);
              output.WriteInt32(Type);
            }
            if (Text.Length != 0) {
              output.WriteRawTag(18);
              output.WriteString(Text);
            }
            if (Link.Length != 0) {
              output.WriteRawTag(26);
              output.WriteString(Link);
            }
            if (DuringTime.Length != 0) {
              output.WriteRawTag(50);
              output.WriteString(DuringTime);
            }
            if (VoiceMd5.Length != 0) {
              output.WriteRawTag(58);
              output.WriteString(VoiceMd5);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (Type != 0) {
              output.WriteRawTag(8);
              output.WriteInt32(Type);
            }
            if (Text.Length != 0) {
              output.WriteRawTag(18);
              output.WriteString(Text);
            }
            if (Link.Length != 0) {
              output.WriteRawTag(26);
              output.WriteString(Link);
            }
            if (DuringTime.Length != 0) {
              output.WriteRawTag(50);
              output.WriteString(DuringTime);
            }
            if (VoiceMd5.Length != 0) {
              output.WriteRawTag(58);
              output.WriteString(VoiceMd5);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int CalculateSize() {
            int size = 0;
            if (Type != 0) {
              size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
            }
            if (Text.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
            }
            if (Link.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(Link);
            }
            if (DuringTime.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(DuringTime);
            }
            if (VoiceMd5.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(VoiceMd5);
            }
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(Abstract other) {
            if (other == null) {
              return;
            }
            if (other.Type != 0) {
              Type = other.Type;
            }
            if (other.Text.Length != 0) {
              Text = other.Text;
            }
            if (other.Link.Length != 0) {
              Link = other.Link;
            }
            if (other.DuringTime.Length != 0) {
              DuringTime = other.DuringTime;
            }
            if (other.VoiceMd5.Length != 0) {
              VoiceMd5 = other.VoiceMd5;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 8: {
                  Type = input.ReadInt32();
                  break;
                }
                case 18: {
                  Text = input.ReadString();
                  break;
                }
                case 26: {
                  Link = input.ReadString();
                  break;
                }
                case 50: {
                  DuringTime = input.ReadString();
                  break;
                }
                case 58: {
                  VoiceMd5 = input.ReadString();
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 8: {
                  Type = input.ReadInt32();
                  break;
                }
                case 18: {
                  Text = input.ReadString();
                  break;
                }
                case 26: {
                  Link = input.ReadString();
                  break;
                }
                case 50: {
                  DuringTime = input.ReadString();
                  break;
                }
                case 58: {
                  VoiceMd5 = input.ReadString();
                  break;
                }
              }
            }
          }
          #endif

        }

      }
      #endregion

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
