// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Media.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Media.proto</summary>
public static partial class MediaReflection {

  #region Descriptor
  /// <summary>File descriptor for Media.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MediaReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtNZWRpYS5wcm90byKUAQoFTWVkaWESDAoEdHlwZRgBIAEoBRIRCglzbWFs",
          "bF9waWMYAiABKAkSDwoHYmlnX3BpYxgDIAEoCRIRCgl3YXRlcl9waWMYBCAB",
          "KAkSDQoFd2lkdGgYCiABKA0SDgoGaGVpZ2h0GAsgASgNEhIKCm9yaWdpbl9w",
          "aWMYDyABKAkSEwoLb3JpZ2luX3NpemUYECABKA1iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Media), global::Media.Parser, new[]{ "Type", "SmallPic", "BigPic", "WaterPic", "Width", "Height", "OriginPic", "OriginSize" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Media : pb::IMessage<Media>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Media> _parser = new pb::MessageParser<Media>(() => new Media());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Media> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MediaReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Media() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Media(Media other) : this() {
    type_ = other.type_;
    smallPic_ = other.smallPic_;
    bigPic_ = other.bigPic_;
    waterPic_ = other.waterPic_;
    width_ = other.width_;
    height_ = other.height_;
    originPic_ = other.originPic_;
    originSize_ = other.originSize_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Media Clone() {
    return new Media(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private int type_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "small_pic" field.</summary>
  public const int SmallPicFieldNumber = 2;
  private string smallPic_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SmallPic {
    get { return smallPic_; }
    set {
      smallPic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "big_pic" field.</summary>
  public const int BigPicFieldNumber = 3;
  private string bigPic_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BigPic {
    get { return bigPic_; }
    set {
      bigPic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "water_pic" field.</summary>
  public const int WaterPicFieldNumber = 4;
  private string waterPic_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string WaterPic {
    get { return waterPic_; }
    set {
      waterPic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "width" field.</summary>
  public const int WidthFieldNumber = 10;
  private uint width_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Width {
    get { return width_; }
    set {
      width_ = value;
    }
  }

  /// <summary>Field number for the "height" field.</summary>
  public const int HeightFieldNumber = 11;
  private uint height_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Height {
    get { return height_; }
    set {
      height_ = value;
    }
  }

  /// <summary>Field number for the "origin_pic" field.</summary>
  public const int OriginPicFieldNumber = 15;
  private string originPic_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string OriginPic {
    get { return originPic_; }
    set {
      originPic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "origin_size" field.</summary>
  public const int OriginSizeFieldNumber = 16;
  private uint originSize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint OriginSize {
    get { return originSize_; }
    set {
      originSize_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Media);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Media other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (SmallPic != other.SmallPic) return false;
    if (BigPic != other.BigPic) return false;
    if (WaterPic != other.WaterPic) return false;
    if (Width != other.Width) return false;
    if (Height != other.Height) return false;
    if (OriginPic != other.OriginPic) return false;
    if (OriginSize != other.OriginSize) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != 0) hash ^= Type.GetHashCode();
    if (SmallPic.Length != 0) hash ^= SmallPic.GetHashCode();
    if (BigPic.Length != 0) hash ^= BigPic.GetHashCode();
    if (WaterPic.Length != 0) hash ^= WaterPic.GetHashCode();
    if (Width != 0) hash ^= Width.GetHashCode();
    if (Height != 0) hash ^= Height.GetHashCode();
    if (OriginPic.Length != 0) hash ^= OriginPic.GetHashCode();
    if (OriginSize != 0) hash ^= OriginSize.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Type);
    }
    if (SmallPic.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(SmallPic);
    }
    if (BigPic.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(BigPic);
    }
    if (WaterPic.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(WaterPic);
    }
    if (Width != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(Width);
    }
    if (Height != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(Height);
    }
    if (OriginPic.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(OriginPic);
    }
    if (OriginSize != 0) {
      output.WriteRawTag(128, 1);
      output.WriteUInt32(OriginSize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Type);
    }
    if (SmallPic.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(SmallPic);
    }
    if (BigPic.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(BigPic);
    }
    if (WaterPic.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(WaterPic);
    }
    if (Width != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(Width);
    }
    if (Height != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(Height);
    }
    if (OriginPic.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(OriginPic);
    }
    if (OriginSize != 0) {
      output.WriteRawTag(128, 1);
      output.WriteUInt32(OriginSize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
    }
    if (SmallPic.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SmallPic);
    }
    if (BigPic.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BigPic);
    }
    if (WaterPic.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(WaterPic);
    }
    if (Width != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Width);
    }
    if (Height != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Height);
    }
    if (OriginPic.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginPic);
    }
    if (OriginSize != 0) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(OriginSize);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Media other) {
    if (other == null) {
      return;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    if (other.SmallPic.Length != 0) {
      SmallPic = other.SmallPic;
    }
    if (other.BigPic.Length != 0) {
      BigPic = other.BigPic;
    }
    if (other.WaterPic.Length != 0) {
      WaterPic = other.WaterPic;
    }
    if (other.Width != 0) {
      Width = other.Width;
    }
    if (other.Height != 0) {
      Height = other.Height;
    }
    if (other.OriginPic.Length != 0) {
      OriginPic = other.OriginPic;
    }
    if (other.OriginSize != 0) {
      OriginSize = other.OriginSize;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = input.ReadInt32();
          break;
        }
        case 18: {
          SmallPic = input.ReadString();
          break;
        }
        case 26: {
          BigPic = input.ReadString();
          break;
        }
        case 34: {
          WaterPic = input.ReadString();
          break;
        }
        case 80: {
          Width = input.ReadUInt32();
          break;
        }
        case 88: {
          Height = input.ReadUInt32();
          break;
        }
        case 122: {
          OriginPic = input.ReadString();
          break;
        }
        case 128: {
          OriginSize = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = input.ReadInt32();
          break;
        }
        case 18: {
          SmallPic = input.ReadString();
          break;
        }
        case 26: {
          BigPic = input.ReadString();
          break;
        }
        case 34: {
          WaterPic = input.ReadString();
          break;
        }
        case 80: {
          Width = input.ReadUInt32();
          break;
        }
        case 88: {
          Height = input.ReadUInt32();
          break;
        }
        case 122: {
          OriginPic = input.ReadString();
          break;
        }
        case 128: {
          OriginSize = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
