// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThreadInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThreadInfo.proto</summary>
public static partial class ThreadInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for ThreadInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThreadInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBUaHJlYWRJbmZvLnByb3RvGgpVc2VyLnByb3RvGgtWb2ljZS5wcm90bxoO",
          "UG9sbEluZm8ucHJvdG8aD1ZpZGVvSW5mby5wcm90bxoPUGJDb250ZW50LnBy",
          "b3RvGgtBZ3JlZS5wcm90bxoLTWVkaWEucHJvdG8izAgKClRocmVhZEluZm8S",
          "CgoCaWQYASABKAMSDQoFdGl0bGUYAyABKAkSEQoJcmVwbHlfbnVtGAQgASgF",
          "EhAKCHZpZXdfbnVtGAUgASgFEhUKDWxhc3RfdGltZV9pbnQYByABKAUSDgoG",
          "aXNfdG9wGAkgASgFEg8KB2lzX2dvb2QYCiABKAUSFwoPaXNfdm9pY2VfdGhy",
          "ZWFkGA8gASgFEhUKBmF1dGhvchgSIAEoCzIFLlVzZXISGgoKdm9pY2VfaW5m",
          "bxgXIAMoCzIGLlZvaWNlEhMKC3RocmVhZF90eXBlGBogASgFEgsKA2ZpZBgb",
          "IAEoAxINCgVmbmFtZRgcIAEoCRITCgtpc19saXZlcG9zdBgeIAEoBRIVCg1m",
          "aXJzdF9wb3N0X2lkGCggASgDEhMKC2NyZWF0ZV90aW1lGC0gASgFEg8KB3Bv",
          "c3RfaWQYNCABKAMSEQoJYXV0aG9yX2lkGDggASgDEg0KBWlzX2FkGDsgASgN",
          "EhwKCXBvbGxfaW5mbxhKIAEoCzIJLlBvbGxJbmZvEh4KCnZpZGVvX2luZm8Y",
          "TyABKAsyCi5WaWRlb0luZm8SHgoWaXNfZ29kdGhyZWFkX3JlY29tbWVuZBhV",
          "IAEoBRIVCgVhZ3JlZRh+IAEoCzIGLkFncmVlEhIKCXNoYXJlX251bRiHASAB",
          "KAUSOQoSb3JpZ2luX3RocmVhZF9pbmZvGI0BIAEoCzIcLlRocmVhZEluZm8u",
          "T3JpZ2luVGhyZWFkSW5mbxInChJmaXJzdF9wb3N0X2NvbnRlbnQYjgEgAygL",
          "MgouUGJDb250ZW50EhgKD2lzX3NoYXJlX3RocmVhZBiPASABKAUSDwoGdGFi",
          "X2lkGK8BIAEoBRITCgppc19kZWxldGVkGLUBIAEoBRIUCgtpc19mcnNfbWFz",
          "axjGASABKAUSMAoNY3VzdG9tX2ZpZ3VyZRjTASABKAsyGC5UaHJlYWRJbmZv",
          "LkN1c3RvbUZpZ3VyZRIuCgxjdXN0b21fc3RhdGUY1AEgASgLMhcuVGhyZWFk",
          "SW5mby5DdXN0b21TdGF0ZRrlAQoQT3JpZ2luVGhyZWFkSW5mbxINCgV0aXRs",
          "ZRgBIAEoCRIVCgVtZWRpYRgCIAMoCzIGLk1lZGlhEg0KBWZuYW1lGAQgASgJ",
          "EgsKA3RpZBgFIAEoCRILCgNmaWQYByABKAMSGgoKdm9pY2VfaW5mbxgMIAMo",
          "CzIGLlZvaWNlEh4KCnZpZGVvX2luZm8YDSABKAsyCi5WaWRlb0luZm8SGwoH",
          "Y29udGVudBgOIAMoCzIKLlBiQ29udGVudBIcCglwb2xsX2luZm8YFSABKAsy",
          "CS5Qb2xsSW5mbxILCgNwaWQYGSABKAMaKAoMQ3VzdG9tRmlndXJlEhgKEGJh",
          "Y2tncm91bmRfdmFsdWUYAyABKAkaHgoLQ3VzdG9tU3RhdGUSDwoHY29udGVu",
          "dBgCIAEoCWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::UserReflection.Descriptor, global::VoiceReflection.Descriptor, global::PollInfoReflection.Descriptor, global::VideoInfoReflection.Descriptor, global::PbContentReflection.Descriptor, global::AgreeReflection.Descriptor, global::MediaReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThreadInfo), global::ThreadInfo.Parser, new[]{ "Id", "Title", "ReplyNum", "ViewNum", "LastTimeInt", "IsTop", "IsGood", "IsVoiceThread", "Author", "VoiceInfo", "ThreadType", "Fid", "Fname", "IsLivepost", "FirstPostId", "CreateTime", "PostId", "AuthorId", "IsAd", "PollInfo", "VideoInfo", "IsGodthreadRecommend", "Agree", "ShareNum", "OriginThreadInfo", "FirstPostContent", "IsShareThread", "TabId", "IsDeleted", "IsFrsMask", "CustomFigure", "CustomState" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ThreadInfo.Types.OriginThreadInfo), global::ThreadInfo.Types.OriginThreadInfo.Parser, new[]{ "Title", "Media", "Fname", "Tid", "Fid", "VoiceInfo", "VideoInfo", "Content", "PollInfo", "Pid" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThreadInfo.Types.CustomFigure), global::ThreadInfo.Types.CustomFigure.Parser, new[]{ "BackgroundValue" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThreadInfo.Types.CustomState), global::ThreadInfo.Types.CustomState.Parser, new[]{ "Content" }, null, null, null, null)})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ThreadInfo : pb::IMessage<ThreadInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThreadInfo> _parser = new pb::MessageParser<ThreadInfo>(() => new ThreadInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThreadInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThreadInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThreadInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThreadInfo(ThreadInfo other) : this() {
    id_ = other.id_;
    title_ = other.title_;
    replyNum_ = other.replyNum_;
    viewNum_ = other.viewNum_;
    lastTimeInt_ = other.lastTimeInt_;
    isTop_ = other.isTop_;
    isGood_ = other.isGood_;
    isVoiceThread_ = other.isVoiceThread_;
    author_ = other.author_ != null ? other.author_.Clone() : null;
    voiceInfo_ = other.voiceInfo_.Clone();
    threadType_ = other.threadType_;
    fid_ = other.fid_;
    fname_ = other.fname_;
    isLivepost_ = other.isLivepost_;
    firstPostId_ = other.firstPostId_;
    createTime_ = other.createTime_;
    postId_ = other.postId_;
    authorId_ = other.authorId_;
    isAd_ = other.isAd_;
    pollInfo_ = other.pollInfo_ != null ? other.pollInfo_.Clone() : null;
    videoInfo_ = other.videoInfo_ != null ? other.videoInfo_.Clone() : null;
    isGodthreadRecommend_ = other.isGodthreadRecommend_;
    agree_ = other.agree_ != null ? other.agree_.Clone() : null;
    shareNum_ = other.shareNum_;
    originThreadInfo_ = other.originThreadInfo_ != null ? other.originThreadInfo_.Clone() : null;
    firstPostContent_ = other.firstPostContent_.Clone();
    isShareThread_ = other.isShareThread_;
    tabId_ = other.tabId_;
    isDeleted_ = other.isDeleted_;
    isFrsMask_ = other.isFrsMask_;
    customFigure_ = other.customFigure_ != null ? other.customFigure_.Clone() : null;
    customState_ = other.customState_ != null ? other.customState_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThreadInfo Clone() {
    return new ThreadInfo(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "title" field.</summary>
  public const int TitleFieldNumber = 3;
  private string title_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Title {
    get { return title_; }
    set {
      title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "reply_num" field.</summary>
  public const int ReplyNumFieldNumber = 4;
  private int replyNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ReplyNum {
    get { return replyNum_; }
    set {
      replyNum_ = value;
    }
  }

  /// <summary>Field number for the "view_num" field.</summary>
  public const int ViewNumFieldNumber = 5;
  private int viewNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ViewNum {
    get { return viewNum_; }
    set {
      viewNum_ = value;
    }
  }

  /// <summary>Field number for the "last_time_int" field.</summary>
  public const int LastTimeIntFieldNumber = 7;
  private int lastTimeInt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LastTimeInt {
    get { return lastTimeInt_; }
    set {
      lastTimeInt_ = value;
    }
  }

  /// <summary>Field number for the "is_top" field.</summary>
  public const int IsTopFieldNumber = 9;
  private int isTop_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsTop {
    get { return isTop_; }
    set {
      isTop_ = value;
    }
  }

  /// <summary>Field number for the "is_good" field.</summary>
  public const int IsGoodFieldNumber = 10;
  private int isGood_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsGood {
    get { return isGood_; }
    set {
      isGood_ = value;
    }
  }

  /// <summary>Field number for the "is_voice_thread" field.</summary>
  public const int IsVoiceThreadFieldNumber = 15;
  private int isVoiceThread_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsVoiceThread {
    get { return isVoiceThread_; }
    set {
      isVoiceThread_ = value;
    }
  }

  /// <summary>Field number for the "author" field.</summary>
  public const int AuthorFieldNumber = 18;
  private global::User author_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::User Author {
    get { return author_; }
    set {
      author_ = value;
    }
  }

  /// <summary>Field number for the "voice_info" field.</summary>
  public const int VoiceInfoFieldNumber = 23;
  private static readonly pb::FieldCodec<global::Voice> _repeated_voiceInfo_codec
      = pb::FieldCodec.ForMessage(186, global::Voice.Parser);
  private readonly pbc::RepeatedField<global::Voice> voiceInfo_ = new pbc::RepeatedField<global::Voice>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Voice> VoiceInfo {
    get { return voiceInfo_; }
  }

  /// <summary>Field number for the "thread_type" field.</summary>
  public const int ThreadTypeFieldNumber = 26;
  private int threadType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ThreadType {
    get { return threadType_; }
    set {
      threadType_ = value;
    }
  }

  /// <summary>Field number for the "fid" field.</summary>
  public const int FidFieldNumber = 27;
  private long fid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Fid {
    get { return fid_; }
    set {
      fid_ = value;
    }
  }

  /// <summary>Field number for the "fname" field.</summary>
  public const int FnameFieldNumber = 28;
  private string fname_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Fname {
    get { return fname_; }
    set {
      fname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "is_livepost" field.</summary>
  public const int IsLivepostFieldNumber = 30;
  private int isLivepost_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsLivepost {
    get { return isLivepost_; }
    set {
      isLivepost_ = value;
    }
  }

  /// <summary>Field number for the "first_post_id" field.</summary>
  public const int FirstPostIdFieldNumber = 40;
  private long firstPostId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long FirstPostId {
    get { return firstPostId_; }
    set {
      firstPostId_ = value;
    }
  }

  /// <summary>Field number for the "create_time" field.</summary>
  public const int CreateTimeFieldNumber = 45;
  private int createTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CreateTime {
    get { return createTime_; }
    set {
      createTime_ = value;
    }
  }

  /// <summary>Field number for the "post_id" field.</summary>
  public const int PostIdFieldNumber = 52;
  private long postId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long PostId {
    get { return postId_; }
    set {
      postId_ = value;
    }
  }

  /// <summary>Field number for the "author_id" field.</summary>
  public const int AuthorIdFieldNumber = 56;
  private long authorId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long AuthorId {
    get { return authorId_; }
    set {
      authorId_ = value;
    }
  }

  /// <summary>Field number for the "is_ad" field.</summary>
  public const int IsAdFieldNumber = 59;
  private uint isAd_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint IsAd {
    get { return isAd_; }
    set {
      isAd_ = value;
    }
  }

  /// <summary>Field number for the "poll_info" field.</summary>
  public const int PollInfoFieldNumber = 74;
  private global::PollInfo pollInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PollInfo PollInfo {
    get { return pollInfo_; }
    set {
      pollInfo_ = value;
    }
  }

  /// <summary>Field number for the "video_info" field.</summary>
  public const int VideoInfoFieldNumber = 79;
  private global::VideoInfo videoInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::VideoInfo VideoInfo {
    get { return videoInfo_; }
    set {
      videoInfo_ = value;
    }
  }

  /// <summary>Field number for the "is_godthread_recommend" field.</summary>
  public const int IsGodthreadRecommendFieldNumber = 85;
  private int isGodthreadRecommend_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsGodthreadRecommend {
    get { return isGodthreadRecommend_; }
    set {
      isGodthreadRecommend_ = value;
    }
  }

  /// <summary>Field number for the "agree" field.</summary>
  public const int AgreeFieldNumber = 126;
  private global::Agree agree_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Agree Agree {
    get { return agree_; }
    set {
      agree_ = value;
    }
  }

  /// <summary>Field number for the "share_num" field.</summary>
  public const int ShareNumFieldNumber = 135;
  private int shareNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ShareNum {
    get { return shareNum_; }
    set {
      shareNum_ = value;
    }
  }

  /// <summary>Field number for the "origin_thread_info" field.</summary>
  public const int OriginThreadInfoFieldNumber = 141;
  private global::ThreadInfo.Types.OriginThreadInfo originThreadInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThreadInfo.Types.OriginThreadInfo OriginThreadInfo {
    get { return originThreadInfo_; }
    set {
      originThreadInfo_ = value;
    }
  }

  /// <summary>Field number for the "first_post_content" field.</summary>
  public const int FirstPostContentFieldNumber = 142;
  private static readonly pb::FieldCodec<global::PbContent> _repeated_firstPostContent_codec
      = pb::FieldCodec.ForMessage(1138, global::PbContent.Parser);
  private readonly pbc::RepeatedField<global::PbContent> firstPostContent_ = new pbc::RepeatedField<global::PbContent>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::PbContent> FirstPostContent {
    get { return firstPostContent_; }
  }

  /// <summary>Field number for the "is_share_thread" field.</summary>
  public const int IsShareThreadFieldNumber = 143;
  private int isShareThread_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsShareThread {
    get { return isShareThread_; }
    set {
      isShareThread_ = value;
    }
  }

  /// <summary>Field number for the "tab_id" field.</summary>
  public const int TabIdFieldNumber = 175;
  private int tabId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TabId {
    get { return tabId_; }
    set {
      tabId_ = value;
    }
  }

  /// <summary>Field number for the "is_deleted" field.</summary>
  public const int IsDeletedFieldNumber = 181;
  private int isDeleted_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsDeleted {
    get { return isDeleted_; }
    set {
      isDeleted_ = value;
    }
  }

  /// <summary>Field number for the "is_frs_mask" field.</summary>
  public const int IsFrsMaskFieldNumber = 198;
  private int isFrsMask_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsFrsMask {
    get { return isFrsMask_; }
    set {
      isFrsMask_ = value;
    }
  }

  /// <summary>Field number for the "custom_figure" field.</summary>
  public const int CustomFigureFieldNumber = 211;
  private global::ThreadInfo.Types.CustomFigure customFigure_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThreadInfo.Types.CustomFigure CustomFigure {
    get { return customFigure_; }
    set {
      customFigure_ = value;
    }
  }

  /// <summary>Field number for the "custom_state" field.</summary>
  public const int CustomStateFieldNumber = 212;
  private global::ThreadInfo.Types.CustomState customState_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThreadInfo.Types.CustomState CustomState {
    get { return customState_; }
    set {
      customState_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThreadInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThreadInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Title != other.Title) return false;
    if (ReplyNum != other.ReplyNum) return false;
    if (ViewNum != other.ViewNum) return false;
    if (LastTimeInt != other.LastTimeInt) return false;
    if (IsTop != other.IsTop) return false;
    if (IsGood != other.IsGood) return false;
    if (IsVoiceThread != other.IsVoiceThread) return false;
    if (!object.Equals(Author, other.Author)) return false;
    if(!voiceInfo_.Equals(other.voiceInfo_)) return false;
    if (ThreadType != other.ThreadType) return false;
    if (Fid != other.Fid) return false;
    if (Fname != other.Fname) return false;
    if (IsLivepost != other.IsLivepost) return false;
    if (FirstPostId != other.FirstPostId) return false;
    if (CreateTime != other.CreateTime) return false;
    if (PostId != other.PostId) return false;
    if (AuthorId != other.AuthorId) return false;
    if (IsAd != other.IsAd) return false;
    if (!object.Equals(PollInfo, other.PollInfo)) return false;
    if (!object.Equals(VideoInfo, other.VideoInfo)) return false;
    if (IsGodthreadRecommend != other.IsGodthreadRecommend) return false;
    if (!object.Equals(Agree, other.Agree)) return false;
    if (ShareNum != other.ShareNum) return false;
    if (!object.Equals(OriginThreadInfo, other.OriginThreadInfo)) return false;
    if(!firstPostContent_.Equals(other.firstPostContent_)) return false;
    if (IsShareThread != other.IsShareThread) return false;
    if (TabId != other.TabId) return false;
    if (IsDeleted != other.IsDeleted) return false;
    if (IsFrsMask != other.IsFrsMask) return false;
    if (!object.Equals(CustomFigure, other.CustomFigure)) return false;
    if (!object.Equals(CustomState, other.CustomState)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Title.Length != 0) hash ^= Title.GetHashCode();
    if (ReplyNum != 0) hash ^= ReplyNum.GetHashCode();
    if (ViewNum != 0) hash ^= ViewNum.GetHashCode();
    if (LastTimeInt != 0) hash ^= LastTimeInt.GetHashCode();
    if (IsTop != 0) hash ^= IsTop.GetHashCode();
    if (IsGood != 0) hash ^= IsGood.GetHashCode();
    if (IsVoiceThread != 0) hash ^= IsVoiceThread.GetHashCode();
    if (author_ != null) hash ^= Author.GetHashCode();
    hash ^= voiceInfo_.GetHashCode();
    if (ThreadType != 0) hash ^= ThreadType.GetHashCode();
    if (Fid != 0L) hash ^= Fid.GetHashCode();
    if (Fname.Length != 0) hash ^= Fname.GetHashCode();
    if (IsLivepost != 0) hash ^= IsLivepost.GetHashCode();
    if (FirstPostId != 0L) hash ^= FirstPostId.GetHashCode();
    if (CreateTime != 0) hash ^= CreateTime.GetHashCode();
    if (PostId != 0L) hash ^= PostId.GetHashCode();
    if (AuthorId != 0L) hash ^= AuthorId.GetHashCode();
    if (IsAd != 0) hash ^= IsAd.GetHashCode();
    if (pollInfo_ != null) hash ^= PollInfo.GetHashCode();
    if (videoInfo_ != null) hash ^= VideoInfo.GetHashCode();
    if (IsGodthreadRecommend != 0) hash ^= IsGodthreadRecommend.GetHashCode();
    if (agree_ != null) hash ^= Agree.GetHashCode();
    if (ShareNum != 0) hash ^= ShareNum.GetHashCode();
    if (originThreadInfo_ != null) hash ^= OriginThreadInfo.GetHashCode();
    hash ^= firstPostContent_.GetHashCode();
    if (IsShareThread != 0) hash ^= IsShareThread.GetHashCode();
    if (TabId != 0) hash ^= TabId.GetHashCode();
    if (IsDeleted != 0) hash ^= IsDeleted.GetHashCode();
    if (IsFrsMask != 0) hash ^= IsFrsMask.GetHashCode();
    if (customFigure_ != null) hash ^= CustomFigure.GetHashCode();
    if (customState_ != null) hash ^= CustomState.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Title.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Title);
    }
    if (ReplyNum != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(ReplyNum);
    }
    if (ViewNum != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(ViewNum);
    }
    if (LastTimeInt != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(LastTimeInt);
    }
    if (IsTop != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(IsTop);
    }
    if (IsGood != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(IsGood);
    }
    if (IsVoiceThread != 0) {
      output.WriteRawTag(120);
      output.WriteInt32(IsVoiceThread);
    }
    if (author_ != null) {
      output.WriteRawTag(146, 1);
      output.WriteMessage(Author);
    }
    voiceInfo_.WriteTo(output, _repeated_voiceInfo_codec);
    if (ThreadType != 0) {
      output.WriteRawTag(208, 1);
      output.WriteInt32(ThreadType);
    }
    if (Fid != 0L) {
      output.WriteRawTag(216, 1);
      output.WriteInt64(Fid);
    }
    if (Fname.Length != 0) {
      output.WriteRawTag(226, 1);
      output.WriteString(Fname);
    }
    if (IsLivepost != 0) {
      output.WriteRawTag(240, 1);
      output.WriteInt32(IsLivepost);
    }
    if (FirstPostId != 0L) {
      output.WriteRawTag(192, 2);
      output.WriteInt64(FirstPostId);
    }
    if (CreateTime != 0) {
      output.WriteRawTag(232, 2);
      output.WriteInt32(CreateTime);
    }
    if (PostId != 0L) {
      output.WriteRawTag(160, 3);
      output.WriteInt64(PostId);
    }
    if (AuthorId != 0L) {
      output.WriteRawTag(192, 3);
      output.WriteInt64(AuthorId);
    }
    if (IsAd != 0) {
      output.WriteRawTag(216, 3);
      output.WriteUInt32(IsAd);
    }
    if (pollInfo_ != null) {
      output.WriteRawTag(210, 4);
      output.WriteMessage(PollInfo);
    }
    if (videoInfo_ != null) {
      output.WriteRawTag(250, 4);
      output.WriteMessage(VideoInfo);
    }
    if (IsGodthreadRecommend != 0) {
      output.WriteRawTag(168, 5);
      output.WriteInt32(IsGodthreadRecommend);
    }
    if (agree_ != null) {
      output.WriteRawTag(242, 7);
      output.WriteMessage(Agree);
    }
    if (ShareNum != 0) {
      output.WriteRawTag(184, 8);
      output.WriteInt32(ShareNum);
    }
    if (originThreadInfo_ != null) {
      output.WriteRawTag(234, 8);
      output.WriteMessage(OriginThreadInfo);
    }
    firstPostContent_.WriteTo(output, _repeated_firstPostContent_codec);
    if (IsShareThread != 0) {
      output.WriteRawTag(248, 8);
      output.WriteInt32(IsShareThread);
    }
    if (TabId != 0) {
      output.WriteRawTag(248, 10);
      output.WriteInt32(TabId);
    }
    if (IsDeleted != 0) {
      output.WriteRawTag(168, 11);
      output.WriteInt32(IsDeleted);
    }
    if (IsFrsMask != 0) {
      output.WriteRawTag(176, 12);
      output.WriteInt32(IsFrsMask);
    }
    if (customFigure_ != null) {
      output.WriteRawTag(154, 13);
      output.WriteMessage(CustomFigure);
    }
    if (customState_ != null) {
      output.WriteRawTag(162, 13);
      output.WriteMessage(CustomState);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Title.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Title);
    }
    if (ReplyNum != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(ReplyNum);
    }
    if (ViewNum != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(ViewNum);
    }
    if (LastTimeInt != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(LastTimeInt);
    }
    if (IsTop != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(IsTop);
    }
    if (IsGood != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(IsGood);
    }
    if (IsVoiceThread != 0) {
      output.WriteRawTag(120);
      output.WriteInt32(IsVoiceThread);
    }
    if (author_ != null) {
      output.WriteRawTag(146, 1);
      output.WriteMessage(Author);
    }
    voiceInfo_.WriteTo(ref output, _repeated_voiceInfo_codec);
    if (ThreadType != 0) {
      output.WriteRawTag(208, 1);
      output.WriteInt32(ThreadType);
    }
    if (Fid != 0L) {
      output.WriteRawTag(216, 1);
      output.WriteInt64(Fid);
    }
    if (Fname.Length != 0) {
      output.WriteRawTag(226, 1);
      output.WriteString(Fname);
    }
    if (IsLivepost != 0) {
      output.WriteRawTag(240, 1);
      output.WriteInt32(IsLivepost);
    }
    if (FirstPostId != 0L) {
      output.WriteRawTag(192, 2);
      output.WriteInt64(FirstPostId);
    }
    if (CreateTime != 0) {
      output.WriteRawTag(232, 2);
      output.WriteInt32(CreateTime);
    }
    if (PostId != 0L) {
      output.WriteRawTag(160, 3);
      output.WriteInt64(PostId);
    }
    if (AuthorId != 0L) {
      output.WriteRawTag(192, 3);
      output.WriteInt64(AuthorId);
    }
    if (IsAd != 0) {
      output.WriteRawTag(216, 3);
      output.WriteUInt32(IsAd);
    }
    if (pollInfo_ != null) {
      output.WriteRawTag(210, 4);
      output.WriteMessage(PollInfo);
    }
    if (videoInfo_ != null) {
      output.WriteRawTag(250, 4);
      output.WriteMessage(VideoInfo);
    }
    if (IsGodthreadRecommend != 0) {
      output.WriteRawTag(168, 5);
      output.WriteInt32(IsGodthreadRecommend);
    }
    if (agree_ != null) {
      output.WriteRawTag(242, 7);
      output.WriteMessage(Agree);
    }
    if (ShareNum != 0) {
      output.WriteRawTag(184, 8);
      output.WriteInt32(ShareNum);
    }
    if (originThreadInfo_ != null) {
      output.WriteRawTag(234, 8);
      output.WriteMessage(OriginThreadInfo);
    }
    firstPostContent_.WriteTo(ref output, _repeated_firstPostContent_codec);
    if (IsShareThread != 0) {
      output.WriteRawTag(248, 8);
      output.WriteInt32(IsShareThread);
    }
    if (TabId != 0) {
      output.WriteRawTag(248, 10);
      output.WriteInt32(TabId);
    }
    if (IsDeleted != 0) {
      output.WriteRawTag(168, 11);
      output.WriteInt32(IsDeleted);
    }
    if (IsFrsMask != 0) {
      output.WriteRawTag(176, 12);
      output.WriteInt32(IsFrsMask);
    }
    if (customFigure_ != null) {
      output.WriteRawTag(154, 13);
      output.WriteMessage(CustomFigure);
    }
    if (customState_ != null) {
      output.WriteRawTag(162, 13);
      output.WriteMessage(CustomState);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Title.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
    }
    if (ReplyNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReplyNum);
    }
    if (ViewNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ViewNum);
    }
    if (LastTimeInt != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastTimeInt);
    }
    if (IsTop != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsTop);
    }
    if (IsGood != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsGood);
    }
    if (IsVoiceThread != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsVoiceThread);
    }
    if (author_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Author);
    }
    size += voiceInfo_.CalculateSize(_repeated_voiceInfo_codec);
    if (ThreadType != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(ThreadType);
    }
    if (Fid != 0L) {
      size += 2 + pb::CodedOutputStream.ComputeInt64Size(Fid);
    }
    if (Fname.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(Fname);
    }
    if (IsLivepost != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IsLivepost);
    }
    if (FirstPostId != 0L) {
      size += 2 + pb::CodedOutputStream.ComputeInt64Size(FirstPostId);
    }
    if (CreateTime != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(CreateTime);
    }
    if (PostId != 0L) {
      size += 2 + pb::CodedOutputStream.ComputeInt64Size(PostId);
    }
    if (AuthorId != 0L) {
      size += 2 + pb::CodedOutputStream.ComputeInt64Size(AuthorId);
    }
    if (IsAd != 0) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IsAd);
    }
    if (pollInfo_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(PollInfo);
    }
    if (videoInfo_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(VideoInfo);
    }
    if (IsGodthreadRecommend != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IsGodthreadRecommend);
    }
    if (agree_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Agree);
    }
    if (ShareNum != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(ShareNum);
    }
    if (originThreadInfo_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(OriginThreadInfo);
    }
    size += firstPostContent_.CalculateSize(_repeated_firstPostContent_codec);
    if (IsShareThread != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IsShareThread);
    }
    if (TabId != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(TabId);
    }
    if (IsDeleted != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IsDeleted);
    }
    if (IsFrsMask != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IsFrsMask);
    }
    if (customFigure_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(CustomFigure);
    }
    if (customState_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(CustomState);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThreadInfo other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Title.Length != 0) {
      Title = other.Title;
    }
    if (other.ReplyNum != 0) {
      ReplyNum = other.ReplyNum;
    }
    if (other.ViewNum != 0) {
      ViewNum = other.ViewNum;
    }
    if (other.LastTimeInt != 0) {
      LastTimeInt = other.LastTimeInt;
    }
    if (other.IsTop != 0) {
      IsTop = other.IsTop;
    }
    if (other.IsGood != 0) {
      IsGood = other.IsGood;
    }
    if (other.IsVoiceThread != 0) {
      IsVoiceThread = other.IsVoiceThread;
    }
    if (other.author_ != null) {
      if (author_ == null) {
        Author = new global::User();
      }
      Author.MergeFrom(other.Author);
    }
    voiceInfo_.Add(other.voiceInfo_);
    if (other.ThreadType != 0) {
      ThreadType = other.ThreadType;
    }
    if (other.Fid != 0L) {
      Fid = other.Fid;
    }
    if (other.Fname.Length != 0) {
      Fname = other.Fname;
    }
    if (other.IsLivepost != 0) {
      IsLivepost = other.IsLivepost;
    }
    if (other.FirstPostId != 0L) {
      FirstPostId = other.FirstPostId;
    }
    if (other.CreateTime != 0) {
      CreateTime = other.CreateTime;
    }
    if (other.PostId != 0L) {
      PostId = other.PostId;
    }
    if (other.AuthorId != 0L) {
      AuthorId = other.AuthorId;
    }
    if (other.IsAd != 0) {
      IsAd = other.IsAd;
    }
    if (other.pollInfo_ != null) {
      if (pollInfo_ == null) {
        PollInfo = new global::PollInfo();
      }
      PollInfo.MergeFrom(other.PollInfo);
    }
    if (other.videoInfo_ != null) {
      if (videoInfo_ == null) {
        VideoInfo = new global::VideoInfo();
      }
      VideoInfo.MergeFrom(other.VideoInfo);
    }
    if (other.IsGodthreadRecommend != 0) {
      IsGodthreadRecommend = other.IsGodthreadRecommend;
    }
    if (other.agree_ != null) {
      if (agree_ == null) {
        Agree = new global::Agree();
      }
      Agree.MergeFrom(other.Agree);
    }
    if (other.ShareNum != 0) {
      ShareNum = other.ShareNum;
    }
    if (other.originThreadInfo_ != null) {
      if (originThreadInfo_ == null) {
        OriginThreadInfo = new global::ThreadInfo.Types.OriginThreadInfo();
      }
      OriginThreadInfo.MergeFrom(other.OriginThreadInfo);
    }
    firstPostContent_.Add(other.firstPostContent_);
    if (other.IsShareThread != 0) {
      IsShareThread = other.IsShareThread;
    }
    if (other.TabId != 0) {
      TabId = other.TabId;
    }
    if (other.IsDeleted != 0) {
      IsDeleted = other.IsDeleted;
    }
    if (other.IsFrsMask != 0) {
      IsFrsMask = other.IsFrsMask;
    }
    if (other.customFigure_ != null) {
      if (customFigure_ == null) {
        CustomFigure = new global::ThreadInfo.Types.CustomFigure();
      }
      CustomFigure.MergeFrom(other.CustomFigure);
    }
    if (other.customState_ != null) {
      if (customState_ == null) {
        CustomState = new global::ThreadInfo.Types.CustomState();
      }
      CustomState.MergeFrom(other.CustomState);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 26: {
          Title = input.ReadString();
          break;
        }
        case 32: {
          ReplyNum = input.ReadInt32();
          break;
        }
        case 40: {
          ViewNum = input.ReadInt32();
          break;
        }
        case 56: {
          LastTimeInt = input.ReadInt32();
          break;
        }
        case 72: {
          IsTop = input.ReadInt32();
          break;
        }
        case 80: {
          IsGood = input.ReadInt32();
          break;
        }
        case 120: {
          IsVoiceThread = input.ReadInt32();
          break;
        }
        case 146: {
          if (author_ == null) {
            Author = new global::User();
          }
          input.ReadMessage(Author);
          break;
        }
        case 186: {
          voiceInfo_.AddEntriesFrom(input, _repeated_voiceInfo_codec);
          break;
        }
        case 208: {
          ThreadType = input.ReadInt32();
          break;
        }
        case 216: {
          Fid = input.ReadInt64();
          break;
        }
        case 226: {
          Fname = input.ReadString();
          break;
        }
        case 240: {
          IsLivepost = input.ReadInt32();
          break;
        }
        case 320: {
          FirstPostId = input.ReadInt64();
          break;
        }
        case 360: {
          CreateTime = input.ReadInt32();
          break;
        }
        case 416: {
          PostId = input.ReadInt64();
          break;
        }
        case 448: {
          AuthorId = input.ReadInt64();
          break;
        }
        case 472: {
          IsAd = input.ReadUInt32();
          break;
        }
        case 594: {
          if (pollInfo_ == null) {
            PollInfo = new global::PollInfo();
          }
          input.ReadMessage(PollInfo);
          break;
        }
        case 634: {
          if (videoInfo_ == null) {
            VideoInfo = new global::VideoInfo();
          }
          input.ReadMessage(VideoInfo);
          break;
        }
        case 680: {
          IsGodthreadRecommend = input.ReadInt32();
          break;
        }
        case 1010: {
          if (agree_ == null) {
            Agree = new global::Agree();
          }
          input.ReadMessage(Agree);
          break;
        }
        case 1080: {
          ShareNum = input.ReadInt32();
          break;
        }
        case 1130: {
          if (originThreadInfo_ == null) {
            OriginThreadInfo = new global::ThreadInfo.Types.OriginThreadInfo();
          }
          input.ReadMessage(OriginThreadInfo);
          break;
        }
        case 1138: {
          firstPostContent_.AddEntriesFrom(input, _repeated_firstPostContent_codec);
          break;
        }
        case 1144: {
          IsShareThread = input.ReadInt32();
          break;
        }
        case 1400: {
          TabId = input.ReadInt32();
          break;
        }
        case 1448: {
          IsDeleted = input.ReadInt32();
          break;
        }
        case 1584: {
          IsFrsMask = input.ReadInt32();
          break;
        }
        case 1690: {
          if (customFigure_ == null) {
            CustomFigure = new global::ThreadInfo.Types.CustomFigure();
          }
          input.ReadMessage(CustomFigure);
          break;
        }
        case 1698: {
          if (customState_ == null) {
            CustomState = new global::ThreadInfo.Types.CustomState();
          }
          input.ReadMessage(CustomState);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 26: {
          Title = input.ReadString();
          break;
        }
        case 32: {
          ReplyNum = input.ReadInt32();
          break;
        }
        case 40: {
          ViewNum = input.ReadInt32();
          break;
        }
        case 56: {
          LastTimeInt = input.ReadInt32();
          break;
        }
        case 72: {
          IsTop = input.ReadInt32();
          break;
        }
        case 80: {
          IsGood = input.ReadInt32();
          break;
        }
        case 120: {
          IsVoiceThread = input.ReadInt32();
          break;
        }
        case 146: {
          if (author_ == null) {
            Author = new global::User();
          }
          input.ReadMessage(Author);
          break;
        }
        case 186: {
          voiceInfo_.AddEntriesFrom(ref input, _repeated_voiceInfo_codec);
          break;
        }
        case 208: {
          ThreadType = input.ReadInt32();
          break;
        }
        case 216: {
          Fid = input.ReadInt64();
          break;
        }
        case 226: {
          Fname = input.ReadString();
          break;
        }
        case 240: {
          IsLivepost = input.ReadInt32();
          break;
        }
        case 320: {
          FirstPostId = input.ReadInt64();
          break;
        }
        case 360: {
          CreateTime = input.ReadInt32();
          break;
        }
        case 416: {
          PostId = input.ReadInt64();
          break;
        }
        case 448: {
          AuthorId = input.ReadInt64();
          break;
        }
        case 472: {
          IsAd = input.ReadUInt32();
          break;
        }
        case 594: {
          if (pollInfo_ == null) {
            PollInfo = new global::PollInfo();
          }
          input.ReadMessage(PollInfo);
          break;
        }
        case 634: {
          if (videoInfo_ == null) {
            VideoInfo = new global::VideoInfo();
          }
          input.ReadMessage(VideoInfo);
          break;
        }
        case 680: {
          IsGodthreadRecommend = input.ReadInt32();
          break;
        }
        case 1010: {
          if (agree_ == null) {
            Agree = new global::Agree();
          }
          input.ReadMessage(Agree);
          break;
        }
        case 1080: {
          ShareNum = input.ReadInt32();
          break;
        }
        case 1130: {
          if (originThreadInfo_ == null) {
            OriginThreadInfo = new global::ThreadInfo.Types.OriginThreadInfo();
          }
          input.ReadMessage(OriginThreadInfo);
          break;
        }
        case 1138: {
          firstPostContent_.AddEntriesFrom(ref input, _repeated_firstPostContent_codec);
          break;
        }
        case 1144: {
          IsShareThread = input.ReadInt32();
          break;
        }
        case 1400: {
          TabId = input.ReadInt32();
          break;
        }
        case 1448: {
          IsDeleted = input.ReadInt32();
          break;
        }
        case 1584: {
          IsFrsMask = input.ReadInt32();
          break;
        }
        case 1690: {
          if (customFigure_ == null) {
            CustomFigure = new global::ThreadInfo.Types.CustomFigure();
          }
          input.ReadMessage(CustomFigure);
          break;
        }
        case 1698: {
          if (customState_ == null) {
            CustomState = new global::ThreadInfo.Types.CustomState();
          }
          input.ReadMessage(CustomState);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the ThreadInfo message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class OriginThreadInfo : pb::IMessage<OriginThreadInfo>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<OriginThreadInfo> _parser = new pb::MessageParser<OriginThreadInfo>(() => new OriginThreadInfo());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<OriginThreadInfo> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::ThreadInfo.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OriginThreadInfo() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OriginThreadInfo(OriginThreadInfo other) : this() {
        title_ = other.title_;
        media_ = other.media_.Clone();
        fname_ = other.fname_;
        tid_ = other.tid_;
        fid_ = other.fid_;
        voiceInfo_ = other.voiceInfo_.Clone();
        videoInfo_ = other.videoInfo_ != null ? other.videoInfo_.Clone() : null;
        content_ = other.content_.Clone();
        pollInfo_ = other.pollInfo_ != null ? other.pollInfo_.Clone() : null;
        pid_ = other.pid_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OriginThreadInfo Clone() {
        return new OriginThreadInfo(this);
      }

      /// <summary>Field number for the "title" field.</summary>
      public const int TitleFieldNumber = 1;
      private string title_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string Title {
        get { return title_; }
        set {
          title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      /// <summary>Field number for the "media" field.</summary>
      public const int MediaFieldNumber = 2;
      private static readonly pb::FieldCodec<global::Media> _repeated_media_codec
          = pb::FieldCodec.ForMessage(18, global::Media.Parser);
      private readonly pbc::RepeatedField<global::Media> media_ = new pbc::RepeatedField<global::Media>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::Media> Media {
        get { return media_; }
      }

      /// <summary>Field number for the "fname" field.</summary>
      public const int FnameFieldNumber = 4;
      private string fname_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string Fname {
        get { return fname_; }
        set {
          fname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      /// <summary>Field number for the "tid" field.</summary>
      public const int TidFieldNumber = 5;
      private string tid_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string Tid {
        get { return tid_; }
        set {
          tid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      /// <summary>Field number for the "fid" field.</summary>
      public const int FidFieldNumber = 7;
      private long fid_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public long Fid {
        get { return fid_; }
        set {
          fid_ = value;
        }
      }

      /// <summary>Field number for the "voice_info" field.</summary>
      public const int VoiceInfoFieldNumber = 12;
      private static readonly pb::FieldCodec<global::Voice> _repeated_voiceInfo_codec
          = pb::FieldCodec.ForMessage(98, global::Voice.Parser);
      private readonly pbc::RepeatedField<global::Voice> voiceInfo_ = new pbc::RepeatedField<global::Voice>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::Voice> VoiceInfo {
        get { return voiceInfo_; }
      }

      /// <summary>Field number for the "video_info" field.</summary>
      public const int VideoInfoFieldNumber = 13;
      private global::VideoInfo videoInfo_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::VideoInfo VideoInfo {
        get { return videoInfo_; }
        set {
          videoInfo_ = value;
        }
      }

      /// <summary>Field number for the "content" field.</summary>
      public const int ContentFieldNumber = 14;
      private static readonly pb::FieldCodec<global::PbContent> _repeated_content_codec
          = pb::FieldCodec.ForMessage(114, global::PbContent.Parser);
      private readonly pbc::RepeatedField<global::PbContent> content_ = new pbc::RepeatedField<global::PbContent>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::PbContent> Content {
        get { return content_; }
      }

      /// <summary>Field number for the "poll_info" field.</summary>
      public const int PollInfoFieldNumber = 21;
      private global::PollInfo pollInfo_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::PollInfo PollInfo {
        get { return pollInfo_; }
        set {
          pollInfo_ = value;
        }
      }

      /// <summary>Field number for the "pid" field.</summary>
      public const int PidFieldNumber = 25;
      private long pid_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public long Pid {
        get { return pid_; }
        set {
          pid_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as OriginThreadInfo);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(OriginThreadInfo other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (Title != other.Title) return false;
        if(!media_.Equals(other.media_)) return false;
        if (Fname != other.Fname) return false;
        if (Tid != other.Tid) return false;
        if (Fid != other.Fid) return false;
        if(!voiceInfo_.Equals(other.voiceInfo_)) return false;
        if (!object.Equals(VideoInfo, other.VideoInfo)) return false;
        if(!content_.Equals(other.content_)) return false;
        if (!object.Equals(PollInfo, other.PollInfo)) return false;
        if (Pid != other.Pid) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (Title.Length != 0) hash ^= Title.GetHashCode();
        hash ^= media_.GetHashCode();
        if (Fname.Length != 0) hash ^= Fname.GetHashCode();
        if (Tid.Length != 0) hash ^= Tid.GetHashCode();
        if (Fid != 0L) hash ^= Fid.GetHashCode();
        hash ^= voiceInfo_.GetHashCode();
        if (videoInfo_ != null) hash ^= VideoInfo.GetHashCode();
        hash ^= content_.GetHashCode();
        if (pollInfo_ != null) hash ^= PollInfo.GetHashCode();
        if (Pid != 0L) hash ^= Pid.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (Title.Length != 0) {
          output.WriteRawTag(10);
          output.WriteString(Title);
        }
        media_.WriteTo(output, _repeated_media_codec);
        if (Fname.Length != 0) {
          output.WriteRawTag(34);
          output.WriteString(Fname);
        }
        if (Tid.Length != 0) {
          output.WriteRawTag(42);
          output.WriteString(Tid);
        }
        if (Fid != 0L) {
          output.WriteRawTag(56);
          output.WriteInt64(Fid);
        }
        voiceInfo_.WriteTo(output, _repeated_voiceInfo_codec);
        if (videoInfo_ != null) {
          output.WriteRawTag(106);
          output.WriteMessage(VideoInfo);
        }
        content_.WriteTo(output, _repeated_content_codec);
        if (pollInfo_ != null) {
          output.WriteRawTag(170, 1);
          output.WriteMessage(PollInfo);
        }
        if (Pid != 0L) {
          output.WriteRawTag(200, 1);
          output.WriteInt64(Pid);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (Title.Length != 0) {
          output.WriteRawTag(10);
          output.WriteString(Title);
        }
        media_.WriteTo(ref output, _repeated_media_codec);
        if (Fname.Length != 0) {
          output.WriteRawTag(34);
          output.WriteString(Fname);
        }
        if (Tid.Length != 0) {
          output.WriteRawTag(42);
          output.WriteString(Tid);
        }
        if (Fid != 0L) {
          output.WriteRawTag(56);
          output.WriteInt64(Fid);
        }
        voiceInfo_.WriteTo(ref output, _repeated_voiceInfo_codec);
        if (videoInfo_ != null) {
          output.WriteRawTag(106);
          output.WriteMessage(VideoInfo);
        }
        content_.WriteTo(ref output, _repeated_content_codec);
        if (pollInfo_ != null) {
          output.WriteRawTag(170, 1);
          output.WriteMessage(PollInfo);
        }
        if (Pid != 0L) {
          output.WriteRawTag(200, 1);
          output.WriteInt64(Pid);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (Title.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
        }
        size += media_.CalculateSize(_repeated_media_codec);
        if (Fname.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Fname);
        }
        if (Tid.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Tid);
        }
        if (Fid != 0L) {
          size += 1 + pb::CodedOutputStream.ComputeInt64Size(Fid);
        }
        size += voiceInfo_.CalculateSize(_repeated_voiceInfo_codec);
        if (videoInfo_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(VideoInfo);
        }
        size += content_.CalculateSize(_repeated_content_codec);
        if (pollInfo_ != null) {
          size += 2 + pb::CodedOutputStream.ComputeMessageSize(PollInfo);
        }
        if (Pid != 0L) {
          size += 2 + pb::CodedOutputStream.ComputeInt64Size(Pid);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(OriginThreadInfo other) {
        if (other == null) {
          return;
        }
        if (other.Title.Length != 0) {
          Title = other.Title;
        }
        media_.Add(other.media_);
        if (other.Fname.Length != 0) {
          Fname = other.Fname;
        }
        if (other.Tid.Length != 0) {
          Tid = other.Tid;
        }
        if (other.Fid != 0L) {
          Fid = other.Fid;
        }
        voiceInfo_.Add(other.voiceInfo_);
        if (other.videoInfo_ != null) {
          if (videoInfo_ == null) {
            VideoInfo = new global::VideoInfo();
          }
          VideoInfo.MergeFrom(other.VideoInfo);
        }
        content_.Add(other.content_);
        if (other.pollInfo_ != null) {
          if (pollInfo_ == null) {
            PollInfo = new global::PollInfo();
          }
          PollInfo.MergeFrom(other.PollInfo);
        }
        if (other.Pid != 0L) {
          Pid = other.Pid;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              Title = input.ReadString();
              break;
            }
            case 18: {
              media_.AddEntriesFrom(input, _repeated_media_codec);
              break;
            }
            case 34: {
              Fname = input.ReadString();
              break;
            }
            case 42: {
              Tid = input.ReadString();
              break;
            }
            case 56: {
              Fid = input.ReadInt64();
              break;
            }
            case 98: {
              voiceInfo_.AddEntriesFrom(input, _repeated_voiceInfo_codec);
              break;
            }
            case 106: {
              if (videoInfo_ == null) {
                VideoInfo = new global::VideoInfo();
              }
              input.ReadMessage(VideoInfo);
              break;
            }
            case 114: {
              content_.AddEntriesFrom(input, _repeated_content_codec);
              break;
            }
            case 170: {
              if (pollInfo_ == null) {
                PollInfo = new global::PollInfo();
              }
              input.ReadMessage(PollInfo);
              break;
            }
            case 200: {
              Pid = input.ReadInt64();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              Title = input.ReadString();
              break;
            }
            case 18: {
              media_.AddEntriesFrom(ref input, _repeated_media_codec);
              break;
            }
            case 34: {
              Fname = input.ReadString();
              break;
            }
            case 42: {
              Tid = input.ReadString();
              break;
            }
            case 56: {
              Fid = input.ReadInt64();
              break;
            }
            case 98: {
              voiceInfo_.AddEntriesFrom(ref input, _repeated_voiceInfo_codec);
              break;
            }
            case 106: {
              if (videoInfo_ == null) {
                VideoInfo = new global::VideoInfo();
              }
              input.ReadMessage(VideoInfo);
              break;
            }
            case 114: {
              content_.AddEntriesFrom(ref input, _repeated_content_codec);
              break;
            }
            case 170: {
              if (pollInfo_ == null) {
                PollInfo = new global::PollInfo();
              }
              input.ReadMessage(PollInfo);
              break;
            }
            case 200: {
              Pid = input.ReadInt64();
              break;
            }
          }
        }
      }
      #endif

    }

    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class CustomFigure : pb::IMessage<CustomFigure>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<CustomFigure> _parser = new pb::MessageParser<CustomFigure>(() => new CustomFigure());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<CustomFigure> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::ThreadInfo.Descriptor.NestedTypes[1]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public CustomFigure() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public CustomFigure(CustomFigure other) : this() {
        backgroundValue_ = other.backgroundValue_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public CustomFigure Clone() {
        return new CustomFigure(this);
      }

      /// <summary>Field number for the "background_value" field.</summary>
      public const int BackgroundValueFieldNumber = 3;
      private string backgroundValue_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string BackgroundValue {
        get { return backgroundValue_; }
        set {
          backgroundValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as CustomFigure);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(CustomFigure other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (BackgroundValue != other.BackgroundValue) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (BackgroundValue.Length != 0) hash ^= BackgroundValue.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (BackgroundValue.Length != 0) {
          output.WriteRawTag(26);
          output.WriteString(BackgroundValue);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (BackgroundValue.Length != 0) {
          output.WriteRawTag(26);
          output.WriteString(BackgroundValue);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (BackgroundValue.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(BackgroundValue);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(CustomFigure other) {
        if (other == null) {
          return;
        }
        if (other.BackgroundValue.Length != 0) {
          BackgroundValue = other.BackgroundValue;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 26: {
              BackgroundValue = input.ReadString();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 26: {
              BackgroundValue = input.ReadString();
              break;
            }
          }
        }
      }
      #endif

    }

    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class CustomState : pb::IMessage<CustomState>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<CustomState> _parser = new pb::MessageParser<CustomState>(() => new CustomState());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<CustomState> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::ThreadInfo.Descriptor.NestedTypes[2]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public CustomState() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public CustomState(CustomState other) : this() {
        content_ = other.content_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public CustomState Clone() {
        return new CustomState(this);
      }

      /// <summary>Field number for the "content" field.</summary>
      public const int ContentFieldNumber = 2;
      private string content_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string Content {
        get { return content_; }
        set {
          content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as CustomState);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(CustomState other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (Content != other.Content) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (Content.Length != 0) hash ^= Content.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (Content.Length != 0) {
          output.WriteRawTag(18);
          output.WriteString(Content);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (Content.Length != 0) {
          output.WriteRawTag(18);
          output.WriteString(Content);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (Content.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(CustomState other) {
        if (other == null) {
          return;
        }
        if (other.Content.Length != 0) {
          Content = other.Content;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 18: {
              Content = input.ReadString();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 18: {
              Content = input.ReadString();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
